- name: data.localdir
  recommendExpression: |
    <#function localDir suffix>
      <#if rcmdMounts?size == 0>
        <#return suffix>
      <#else>
        <#local dirs = []>
        <#list rcmdMounts?sort as mnt>
         <#local dirs = dirs + [mnt + suffix]>
        </#list>
        <#return dirs?join(",")>
      </#if>
    </#function>
    ${localDir("/kundb1/")}
  isNodeSpecific: true 
  defaultValue: null
  valueType: ABSOLUTE_PATH
  scope: !<RoleTypes>
    roleTypes: [KUNCTLD, COMPUTE_NODE, KUNTABLET_MASTER, KUNTABLET_REPLICA, KUNTABLET_RDONLY, KUNGATE]
  onDeps: []
  groups: [kundb-env.sh]
  visibility: READ_WRITE

- name: kundb.cellname 
  recommendExpression: transwarp 
  defaultValue: transwarp 
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: kundb.keyspace 
  recommendExpression: jzpt 
  defaultValue: jzpt 
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: kundb.context.path
  recommendExpression: /check/status
  defaultValue: /check/status
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: HIDDEN

- name: shard.default_dbname 
  recommendExpression: vt_jzpt 
  defaultValue: vt_jzpt
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: computenode.default_dbname 
  recommendExpression: jzpt 
  defaultValue: jzpt
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: shard.uid_base 
  recommendExpression: 100
  defaultValue: 100 
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: computenode.uid_base 
  recommendExpression: 800
  defaultValue: 800 
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: master.mysql.innodb_page_size
  recommendExpression: 32768 
  defaultValue: null
  valueType: BYTES 
  isNodeSpecific: true
  scope: !<RoleTypes>
    roleTypes: [KUNTABLET_MASTER]
  onDeps: []
  groups: [master_mysql56.cnf]
  visibility: READ_WRITE

- name: master.mysql.innodb_buffer_pool_size
  recommendExpression: 20G 
  defaultValue: 20G 
  valueType: GB
  isNodeSpecific: true
  scope: !<RoleTypes>
    roleTypes: [KUNTABLET_MASTER]
  onDeps: []
  groups: [master_mysql56.cnf]
  visibility: READ_WRITE

- name: replica.mysql.innodb_buffer_pool_size
  recommendExpression: 20G 
  defaultValue: 20G 
  valueType: GB
  isNodeSpecific: true
  scope: !<RoleTypes>
    roleTypes: [KUNTABLET_REPLICA]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: rdonly.mysql.innodb_buffer_pool_size
  recommendExpression: 20 
  defaultValue: null
  valueType: GB
  isNodeSpecific: true
  scope: !<RoleTypes>
    roleTypes: [KUNTABLET_RDONLY]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: master.debug.port
  recommendExpression: ${15100 + 10 * (currentRoleGroupsCount - 1)}
  defaultValue: NULL
  valueType: PORT
  isNodeSpecific: true
  scope: !<RoleTypes>
    roleTypes: [KUNTABLET_MASTER]
  onDeps: []
  groups: []
  visibility: READ_WRITE
  isSupportMultiInstances: true
  domain: !<RoleTypes>
    roleTypes: [KUNTABLET_MASTER]

- name: replica.debug.port
  recommendExpression: ${15101 + 10 * (currentRoleGroupsCount - 1)}
  defaultValue: NULL
  valueType: PORT
  isNodeSpecific: true
  scope: !<RoleTypes>
    roleTypes: [KUNTABLET_REPLICA]
  onDeps: []
  groups: []
  visibility: READ_WRITE
  isSupportMultiInstances: true
  domain: !<RoleTypes>
    roleTypes: [KUNTABLET_REPLICA]

- name: rdonly.debug.port
  recommendExpression: ${15102 + 10 * (currentRoleGroupsCount - 1)}
  defaultValue: NULL
  valueType: PORT
  isNodeSpecific: true
  scope: !<RoleTypes>
    roleTypes: [KUNTABLET_RDONLY]
  onDeps: []
  groups: []
  visibility: READ_WRITE
  isSupportMultiInstances: true
  domain: !<RoleTypes>
    roleTypes: [KUNTABLET_RDONLY]

- name: kunctld.debug.port
  recommendExpression: 15000
  defaultValue: NULL
  valueType: PORT
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: computenode.debug.port
  recommendExpression: 15800
  defaultValue: NULL
  valueType: PORT
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: kungate.debug.port
  recommendExpression: 15001
  defaultValue: NULL
  valueType: PORT
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: kungate.server.port
  recommendExpression: 15306
  defaultValue: NULL
  valueType: PORT
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: master.port_base 
  recommendExpression: 15000 

- name: master.port_base 
  recommendExpression: 15000 
  defaultValue: 15000 
  valueType: PORT 
  isNodeSpecific: true 
  scope: !<RoleTypes>
    roleTypes: [KUNTABLET_MASTER]
  onDeps: []
  groups: [master_conf.sh]
  visibility: READ_WRITE

- name: master.grpc.port_base 
  recommendExpression: 16000 
  defaultValue: 16000 
  valueType: PORT 
  isNodeSpecific: true
  scope: !<RoleTypes>
    roleTypes: [KUNTABLET_MASTER]
  onDeps: []
  groups: [master_conf.sh]
  visibility: READ_WRITE

- name: master.mysql.port_base 
  recommendExpression: 17000 
  defaultValue: 17000 
  valueType: PORT 
  isNodeSpecific: true 
  scope: !<RoleTypes>
    roleTypes: [KUNTABLET_MASTER]
  onDeps: []
  groups: [master_conf.sh]
  visibility: READ_WRITE

- name: replica.port_base 
  recommendExpression: 15000 
  defaultValue: 15000 
  valueType: PORT 
  isNodeSpecific: true 
  scope: !<RoleTypes>
    roleTypes: [KUNTABLET_REPLICA]
  onDeps: []
  groups: [replica_conf.sh]
  visibility: READ_WRITE

- name: replica.grpc.port_base 
  recommendExpression: 16000 
  defaultValue: 16000 
  valueType: PORT 
  isNodeSpecific: true
  scope: !<RoleTypes>
    roleTypes: [KUNTABLET_REPLICA]
  onDeps: []
  groups: [replica_conf.sh]
  visibility: READ_WRITE

- name: replica.mysql.port_base 
  recommendExpression: 17000 
  defaultValue: 17000 
  valueType: PORT 
  isNodeSpecific: true 
  scope: !<RoleTypes>
    roleTypes: [KUNTABLET_REPLICA]
  onDeps: []
  groups: [replica_conf.sh]
  visibility: READ_WRITE

- name: rdonly.port_base 
  recommendExpression: 15000 
  defaultValue: 15000 
  valueType: PORT 
  isNodeSpecific: true 
  scope: !<RoleTypes>
    roleTypes: [KUNTABLET_RDONLY]
  onDeps: []
  groups: [rdonly_conf.sh]
  visibility: READ_WRITE

- name: rdonly.grpc.port_base 
  recommendExpression: 16000 
  defaultValue: 16000 
  valueType: PORT 
  isNodeSpecific: true
  scope: !<RoleTypes>
    roleTypes: [KUNTABLET_RDONLY]
  onDeps: []
  groups: [replica_conf.sh]
  visibility: READ_WRITE

- name: rdonly.mysql.port_base 
  recommendExpression: 17000 
  defaultValue: 17000 
  valueType: PORT 
  isNodeSpecific: true 
  scope: !<RoleTypes>
    roleTypes: [KUNTABLET_RDONLY]
  onDeps: []
  groups: [rdonly_conf.sh]
  visibility: READ_WRITE

- name: compute.optimizer_switch 
  recommendExpression: "fedx_scan_mode_olap=off,fedx_mrr=on,fedx_cbo_with_actual_records=on,fedx_sharded_read=on,fedx_range_read=on,fedx_auto_partial_read_on_limit=on,fedx_cache_range_info=on"
  defaultValue: "fedx_scan_mode_olap=off,fedx_mrr=on,fedx_cbo_with_actual_records=on,fedx_sharded_read=on,fedx_range_read=on,fedx_auto_partial_read_on_limit=on,fedx_cache_range_info=on"
  valueType: STRING 
  isNodeSpecific: true 
  scope: !<RoleTypes>
    roleTypes: [COMPUTE_NODE]
  onDeps: []
  groups: [mfed.cnf]
  visibility: READ_WRITE

- name: compute.fedx_bkah_size
  recommendExpression: 1024 
  defaultValue: 1024 
  valueType: NON_NEG_INT 
  isNodeSpecific: true 
  scope: !<RoleTypes>
    roleTypes: [COMPUTE_NODE]
  onDeps: []
  groups: [mfed.cnf]
  visibility: READ_WRITE

- name: compute.fedx_vitess_min_str_len_for_cbo
  recommendExpression: 2 
  defaultValue: 2 
  valueType: NON_NEG_INT 
  isNodeSpecific: true 
  scope: !<RoleTypes>
    roleTypes: [COMPUTE_NODE]
  onDeps: []
  groups: [mfed.cnf]
  visibility: READ_WRITE

- name: compute.fedx_small_table_threshold 
  recommendExpression: 20000 
  defaultValue: 20000 
  valueType: NON_NEG_INT 
  isNodeSpecific: true 
  scope: !<RoleTypes>
    roleTypes: [COMPUTE_NODE]
  onDeps: []
  groups: [mfed.cnf]
  visibility: READ_WRITE

- name: compute.fedx_valid_index_cardinality_percent 
  recommendExpression: 7 
  defaultValue: 7
  valueType: NON_NEG_INT 
  isNodeSpecific: true 
  scope: !<RoleTypes>
    roleTypes: [COMPUTE_NODE]
  onDeps: []
  groups: [mfed.cnf]
  visibility: READ_WRITE

- name: compute.fedx_valid_index_cardinality_minvalue
  recommendExpression: 10 
  defaultValue: 10 
  valueType: NON_NEG_INT 
  isNodeSpecific: true 
  scope: !<RoleTypes>
    roleTypes: [COMPUTE_NODE]
  onDeps: []
  groups: [mfed.cnf]
  visibility: READ_WRITE

- name: kunctld.memory
  recommendExpression: 8192 
  defaultValue: null
  valueType: MB
  isNodeSpecific: true
  scope: !<RoleTypes>
    roleTypes: [KUNCTLD]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: computenode.memory
  recommendExpression: 8192
  defaultValue: null
  valueType: MB
  isNodeSpecific: true
  scope: !<RoleTypes>
    roleTypes: [COMPUTE_NODE]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: KunGate.memory
  recommendExpression: 4096
  defaultValue: null
  valueType: MB
  isNodeSpecific: true
  scope: !<RoleTypes>
    roleTypes: [KUNGATE]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: kunctld.container.requests.memory
  recommendExpression: -1
  defaultValue: null
  valueType: GB
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: master.container.requests.memory
  recommendExpression: -1
  defaultValue: null
  valueType: GB
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: replica.container.requests.memory
  recommendExpression: -1
  defaultValue: null
  valueType: GB
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: rdonly.container.requests.memory
  recommendExpression: -1
  defaultValue: null
  valueType: GB
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: READ_WRITE


- name: computenode.container.requests.memory
  recommendExpression: -1 
  defaultValue: null
  valueType: GB
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: KunGate.container.requests.memory
  recommendExpression: -1
  defaultValue: null
  valueType: GB
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: kunctld.container.limits.memory
  recommendExpression: -1
  defaultValue: null
  valueType: GB
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: master.container.limits.memory
  recommendExpression: -1
  defaultValue: null
  valueType: GB
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: replica.container.limits.memory
  recommendExpression: -1
  defaultValue: null
  valueType: GB
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: rdonly.container.limits.memory
  recommendExpression: -1
  defaultValue: null
  valueType: GB
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: computenode.container.limits.memory
  recommendExpression: -1
  defaultValue: null
  valueType: GB
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: KunGate.container.limits.memory
  recommendExpression: -1
  defaultValue: null
  valueType: GB
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: READ_WRITE
