apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    transwarp.name: coredns-conf-cm
  name: coredns-conf-cm
  namespace: kube-system
data:
  Corefile: |
    .:${service['kube.dns.dnsmasq.port']} {
      debug
      log
      cache 30
      errors
      health :${service['kube.dns.kubedns.healthzport']}
      kubernetes transwarp.local in-addr.arpa ip6.arpa {
          pods verified
      }
      loadbalance round_robin
      hosts {
        114.114.114.114 .
        fallthrough
      }
      forward . 114.114.114.114 {
        health_check 5s
      }
    }
