- name: tdt.server.port
  recommendExpression: 8100
  defaultValue: null
  valueType: PORT
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: ["tdt-site.xml"]
  visibility: READ_WRITE
  
- name: tdt.persistence.user.name
  recommendExpression: tdtuser
  defaultValue: null
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: ["tdt-site.xml"]
  visibility: READ_WRITE

- name: tdt.persistence.password
  recommendExpression: password
  defaultValue: null
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: ["tdt-site.xml"]
  visibility: PASSWORD

- name: tdt.inceptor.ldap.username
  recommendExpression: tdtuser
  defaultValue: null
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: ["tdt-site.xml"]
  visibility: READ_WRITE

- name: tdt.inceptor.ldap.password
  recommendExpression: password
  defaultValue: null
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: ["tdt-site.xml"]
  visibility: READ_WRITE
  
- name: tdt.task.live.time
  recommendExpression: 12hour
  defaultValue: null
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: ["tdt-site.xml"]
  visibility: READ_WRITE  
  
- name: tdt.task.scavenger.check.period
  recommendExpression: 30min
  defaultValue: null
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: ["tdt-site.xml"]
  visibility: READ_WRITE     
  
- name: tdt.task.max.accept.size
  recommendExpression: 10000
  defaultValue: null
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: ["tdt-site.xml"]
  visibility: READ_WRITE       
  
- name: tdt.task.max.concurrent.size
  recommendExpression: 100
  defaultValue: null
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: ["tdt-site.xml"]
  visibility: READ_WRITE

- name: tdt.thread.max.concurrent.size
  recommendExpression: 20
  defaultValue: null
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: ["tdt-site.xml"]
  visibility: READ_WRITE

- name: tdt.container.limits.memory
  recommendExpression: -1
  defaultValue: null
  valueType: GB
  scope: !<RoleTypes>
    roleTypes: [TDT_SERVER]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: tdt.container.limits.cpu
  recommendExpression: -1
  defaultValue: null
  valueType: NON_NEG_INT
  scope: !<RoleTypes>
    roleTypes: [TDT_SERVER]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: tdt.container.requests.memory
  recommendExpression: -1
  defaultValue: null
  valueType: GB
  scope: !<RoleTypes>
    roleTypes: [TDT_SERVER]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: tdt.container.requests.cpu
  recommendExpression: -1
  defaultValue: null
  valueType: NON_NEG_INT
  scope: !<RoleTypes>
    roleTypes: [TDT_SERVER]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: tdt.memory.ratio
  recommendExpression: 0.9
  defaultValue: null
  valueType: FLOAT
  scope: !<RoleTypes>
    roleTypes: [TDT_SERVER]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: tdt.kafka.bootstrap.servers
  recommendExpression: null
  defaultValue: null
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: ["tdt-site.xml"]
  visibility: READ_WRITE