# APPLICATION CONFIG
- name: thingercloud.db.username
  recommendExpression: thinger
  defaultValue: null
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: thingercloud.db.password
  recommendExpression: password
  defaultValue: null
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: PASSWORD

- name: thingercloud.consul.port
  recommendExpression: 8500
  defaultValue: null
  valueType: PORT
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: thingercloud.frontend.port
  recommendExpression: 11081
  defaultValue: null
  valueType: PORT
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: thingercloud.gateway.port
  recommendExpression: 11080
  defaultValue: null
  valueType: PORT
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: READ_WRITE

# CONTAINER CONFIG
- name: thingercloud.frontend.container.limits.memory
  recommendExpression: -1
  defaultValue: null
  valueType: GB
  scope: !<RoleTypes>
    roleTypes: [MIRROR_USERPROFILE]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: thingercloud.frontend.container.limits.cpu
  recommendExpression: -1
  defaultValue: null
  valueType: NON_NEG_INT
  scope: !<RoleTypes>
    roleTypes: [MIRROR_USERPROFILE]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: thingercloud.frontend.container.requests.memory
  recommendExpression: -1
  defaultValue: null
  valueType: GB
  scope: !<RoleTypes>
    roleTypes: [MIRROR_USERPROFILE]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: thingercloud.frontend.container.requests.cpu
  recommendExpression: -1
  defaultValue: null
  valueType: NON_NEG_INT
  scope: !<RoleTypes>
    roleTypes: [MIRROR_USERPROFILE]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: thingercloud.gateway.container.limits.memory
  recommendExpression: -1
  defaultValue: null
  valueType: GB
  scope: !<RoleTypes>
    roleTypes: [MIRROR_USERPROFILE]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: thingercloud.gateway.container.limits.cpu
  recommendExpression: -1
  defaultValue: null
  valueType: NON_NEG_INT
  scope: !<RoleTypes>
    roleTypes: [MIRROR_USERPROFILE]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: thingercloud.gateway.container.requests.memory
  recommendExpression: -1
  defaultValue: null
  valueType: GB
  scope: !<RoleTypes>
    roleTypes: [MIRROR_USERPROFILE]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: thingercloud.gateway.container.requests.cpu
  recommendExpression: -1
  defaultValue: null
  valueType: NON_NEG_INT
  scope: !<RoleTypes>
    roleTypes: [MIRROR_USERPROFILE]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: thingercloud.consul.container.limits.memory
  recommendExpression: -1
  defaultValue: null
  valueType: GB
  scope: !<RoleTypes>
    roleTypes: [MIRROR_USERPROFILE]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: thingercloud.consul.container.limits.cpu
  recommendExpression: -1
  defaultValue: null
  valueType: NON_NEG_INT
  scope: !<RoleTypes>
    roleTypes: [MIRROR_USERPROFILE]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: thingercloud.consul.container.requests.memory
  recommendExpression: -1
  defaultValue: null
  valueType: GB
  scope: !<RoleTypes>
    roleTypes: [MIRROR_USERPROFILE]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: thingercloud.consul.container.requests.cpu
  recommendExpression: -1
  defaultValue: null
  valueType: NON_NEG_INT
  scope: !<RoleTypes>
    roleTypes: [MIRROR_USERPROFILE]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: thingercloud.edgemgr.container.limits.memory
  recommendExpression: -1
  defaultValue: null
  valueType: GB
  scope: !<RoleTypes>
    roleTypes: [MIRROR_USERPROFILE]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: thingercloud.edgemgr.container.limits.cpu
  recommendExpression: -1
  defaultValue: null
  valueType: NON_NEG_INT
  scope: !<RoleTypes>
    roleTypes: [MIRROR_USERPROFILE]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: thingercloud.edgemgr.container.requests.memory
  recommendExpression: -1
  defaultValue: null
  valueType: GB
  scope: !<RoleTypes>
    roleTypes: [MIRROR_USERPROFILE]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: thingercloud.edgemgr.container.requests.cpu
  recommendExpression: -1
  defaultValue: null
  valueType: NON_NEG_INT
  scope: !<RoleTypes>
    roleTypes: [MIRROR_USERPROFILE]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: thingercloud.appmgr.container.limits.memory
  recommendExpression: -1
  defaultValue: null
  valueType: GB
  scope: !<RoleTypes>
    roleTypes: [MIRROR_USERPROFILE]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: thingercloud.appmgr.container.limits.cpu
  recommendExpression: -1
  defaultValue: null
  valueType: NON_NEG_INT
  scope: !<RoleTypes>
    roleTypes: [MIRROR_USERPROFILE]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: thingercloud.appmgr.container.requests.memory
  recommendExpression: -1
  defaultValue: null
  valueType: GB
  scope: !<RoleTypes>
    roleTypes: [MIRROR_USERPROFILE]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: thingercloud.appmgr.container.requests.cpu
  recommendExpression: -1
  defaultValue: null
  valueType: NON_NEG_INT
  scope: !<RoleTypes>
    roleTypes: [MIRROR_USERPROFILE]
  onDeps: []
  groups: []
  visibility: READ_WRITE
