# application-prod.properties
- name: mirror.userprofile.backend.port
  recommendExpression: 8887
  defaultValue: null
  valueType: PORT
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: mirror.userprofile.frontend.port
  recommendExpression: 8888
  defaultValue: null
  valueType: PORT
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: javax.jdo.option.ConnectionUserName
  recommendExpression: mirroruser
  defaultValue: null
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: javax.jdo.option.ConnectionPassword
  recommendExpression: password
  defaultValue: null
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: PASSWORD


#inceptor.properties

- name: mirror.userprofile.inceptor.ldap.username
  recommendExpression: mirror
  defaultValue: null
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: mirror.userprofile.inceptor.ldap.password
  recommendExpression: password
  defaultValue: null
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: PASSWORD

- name: mirror.userprofile.backend.limits.memory
  recommendExpression: -1
  defaultValue: null
  valueType: GB
  scope: !<RoleTypes>
    roleTypes: [MIRROR_USERPROFILE_BACKEND]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: mirror.userprofile.backend.limits.cpu
  recommendExpression: -1
  defaultValue: null
  valueType: NON_NEG_INT
  scope: !<RoleTypes>
    roleTypes: [MIRROR_USERPROFILE_BACKEND]
  onDeps: []
  groups: []
  visibility: READ_WRITE


- name: mirror.userprofile.backend.requests.memory
  recommendExpression: -1
  defaultValue: null
  valueType: GB
  scope: !<RoleTypes>
    roleTypes: [MIRROR_USERPROFILE_BACKEND]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: mirror.userprofile.backend.requests.cpu
  recommendExpression: -1
  defaultValue: null
  valueType: NON_NEG_INT
  scope: !<RoleTypes>
    roleTypes: [MIRROR_USERPROFILE_BACKEND]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: mirror.userprofile.frontend.limits.memory
  recommendExpression: -1
  defaultValue: null
  valueType: GB
  scope: !<RoleTypes>
    roleTypes: [MIRROR_USERPROFILE_FRONTEND]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: mirror.userprofile.frontend.limits.cpu
  recommendExpression: -1
  defaultValue: null
  valueType: NON_NEG_INT
  scope: !<RoleTypes>
    roleTypes: [MIRROR_USERPROFILE_FRONTEND]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: mirror.userprofile.frontend.requests.memory
  recommendExpression: -1
  defaultValue: null
  valueType: GB
  scope: !<RoleTypes>
    roleTypes: [MIRROR_USERPROFILE_FRONTEND]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: mirror.userprofile.frontend.requests.cpu
  recommendExpression: -1
  defaultValue: null
  valueType: NON_NEG_INT
  scope: !<RoleTypes>
    roleTypes: [MIRROR_USERPROFILE_FRONTEND]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: mirror.distributed.database.type
  recommendExpression: inceptor
  defaultValue: null
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: mirror.superuser.username
  recommendExpression: mirror_admin
  defaultValue: null
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: mirror.superuser.password
  recommendExpression: Transwarp4T
  defaultValue: null
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: workflow.client.username
  recommendExpression: workflow
  defaultValue: null
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: workflow.client.password
  recommendExpression: Transwarp4T
  defaultValue: null
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: workflow.domain.id
  recommendExpression: 0
  defaultValue: null
  valueType: NON_NEG_INT
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: spark.sql.warehouse.dir
  recommendExpression: |
    <#function hdfsUri path>
      <#local hdfs=dependencies['HDFS']>
      <#if hdfs['nameservices']?? && hdfs['nameservices']?size gt 0>
        <#local hostPort=hdfs['nameservices'][0]>
      <#else>
        <#local host=hdfs['roles']['HDFS_NAMENODE'][0]['hostname']>
        <#if hdfs['namenode.rpc-port']??>
          <#local port=hdfs['namenode.rpc-port']>
        </#if>
        <#if hdfs[host]?? && hdfs[host]['namenode.rpc-port']??>
          <#local port=hdfs[host]['namenode.rpc-port']>
        </#if>
        <#local hostPort=host + ':' + port>
      </#if>
      <#return 'hdfs://' + hostPort + path>
    </#function>
    ${hdfsUri("/" + dependencies.INCEPTOR.sid + '/user/hive/warehouse')}
  defaultValue: "/user/hive/warehouse"
  valueType: URI
  scope: !<ServiceLevel> {}
  onDeps: ['HDFS','INCEPTOR']
  groups: []
  visibility: READ_WRITE

- name: task.pool.size
  recommendExpression: 100
  defaultValue: null
  valueType: NON_NEG_INT
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: task.max.concurrency
  recommendExpression: 10
  defaultValue: null
  valueType: NON_NEG_INT
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: task.timeout
  recommendExpression: 3600000
  defaultValue: null
  valueType: MILLISECONDS
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: mirror.execute.cycle
  recommendExpression: 3000
  defaultValue: null
  valueType: MILLISECONDS
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: READ_WRITE