- name: dbaservice.container.limits.memory
  recommendExpression: -1
  defaultValue: null
  valueType: FLOAT
  scope: !<RoleTypes>
    roleTypes: [DBA_SERVICE_SERVER]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: dbaservice.container.limits.cpu
  recommendExpression: -1
  defaultValue: null
  valueType: FLOAT
  scope: !<RoleTypes>
    roleTypes: [DBA_SERVICE_SERVER]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: dbaservice.container.requests.memory
  recommendExpression: -1
  defaultValue: null
  valueType: FLOAT
  scope: !<RoleTypes>
    roleTypes: [DBA_SERVICE_SERVER]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: dbaservice.container.requests.cpu
  recommendExpression: -1
  defaultValue: null
  valueType: FLOAT
  scope: !<RoleTypes>
    roleTypes: [DBA_SERVICE_SERVER]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: dbaservice.ui.port
  recommendExpression: 4040
  defaultValue: null
  valueType: PORT
  scope: !<RoleTypes>
    roleTypes: [DBA_SERVICE_SERVER]
  onDeps: []
  groups: ["application.yml"]
  visibility: READ_WRITE

- name: dbaservice.aiops.ui.port
  recommendExpression: 8008
  defaultValue: null
  valueType: PORT
  scope: !<RoleTypes>
    roleTypes: [DBA_SERVICE_SERVER]
  onDeps: []
  groups: ["application.yml", "aiops.yml"]
  visibility: READ_WRITE

- name: dbaservice.security.enabled
  recommendExpression: false
  defaultValue: false
  valueType: BOOL
  scope: !<RoleTypes>
    roleTypes: [DBA_SERVICE_SERVER]
  onDeps: []
  groups: ["application.yml"]
  visibility: READ_WRITE

- name: dbaservice.inceptor.limit.status
  recommendExpression: 10000
  defaultValue: null
  valueType: NON_NEG_INT
  scope: !<RoleTypes>
    roleTypes: [DBA_SERVICE_SERVER]
  onDeps: []
  groups: ["application.yml"]
  visibility: READ_WRITE

- name: dbaservice.inceptor.limit.session
  recommendExpression: 10000
  defaultValue: null
  valueType: NON_NEG_INT
  scope: !<RoleTypes>
    roleTypes: [DBA_SERVICE_SERVER]
  onDeps: []
  groups: ["application.yml"]
  visibility: READ_WRITE

- name: dbaservice.inceptor.limit.completeSql
  recommendExpression: 5000
  defaultValue: null
  valueType: NON_NEG_INT
  scope: !<RoleTypes>
    roleTypes: [DBA_SERVICE_SERVER]
  onDeps: []
  groups: ["application.yml"]
  visibility: READ_WRITE

- name: dbaservice.inceptor.limit.incompleteSql
  recommendExpression: 10000
  defaultValue: null
  valueType: NON_NEG_INT
  scope: !<RoleTypes>
    roleTypes: [DBA_SERVICE_SERVER]
  onDeps: []
  groups: ["application.yml"]
  visibility: READ_WRITE

- name: dbaservice.inceptor.limit.errorSql
  recommendExpression: 10000
  defaultValue: null
  valueType: NON_NEG_INT
  scope: !<RoleTypes>
    roleTypes: [DBA_SERVICE_SERVER]
  onDeps: []
  groups: ["application.yml"]
  visibility: READ_WRITE

- name: dbaservice.inceptor.limit.incompleteJob
  recommendExpression: 20000
  defaultValue: null
  valueType: NON_NEG_INT
  scope: !<RoleTypes>
    roleTypes: [DBA_SERVICE_SERVER]
  onDeps: []
  groups: ["application.yml"]
  visibility: READ_WRITE

- name: dbaservice.inceptor.limit.incompleteStage
  recommendExpression: 50000
  defaultValue: null
  valueType: NON_NEG_INT
  scope: !<RoleTypes>
    roleTypes: [DBA_SERVICE_SERVER]
  onDeps: []
  groups: ["application.yml"]
  visibility: READ_WRITE

- name: dbaservice.inceptor.limit.incompleteTask
  recommendExpression: 1000000
  defaultValue: null
  valueType: NON_NEG_INT
  scope: !<RoleTypes>
    roleTypes: [DBA_SERVICE_SERVER]
  onDeps: []
  groups: ["application.yml"]
  visibility: READ_WRITE

- name: dbaservice.inceptor.limit.incompleteLocalTask
  recommendExpression: 1000000
  defaultValue: null
  valueType: NON_NEG_INT
  scope: !<RoleTypes>
    roleTypes: [DBA_SERVICE_SERVER]
  onDeps: []
  groups: ["application.yml"]
  visibility: READ_WRITE

- name: dbaservice.inceptor.limit.task
  recommendExpression: 5000000
  defaultValue: null
  valueType: NON_NEG_INT
  scope: !<RoleTypes>
    roleTypes: [DBA_SERVICE_SERVER]
  onDeps: []
  groups: ["application.yml"]
  visibility: READ_WRITE

- name: dbaservice.inceptor.limit.noParentJob
  recommendExpression: 20000
  defaultValue: null
  valueType: NON_NEG_INT
  scope: !<RoleTypes>
    roleTypes: [DBA_SERVICE_SERVER]
  onDeps: []
  groups: ["application.yml"]
  visibility: READ_WRITE

- name: dbaservice.inceptor.limit.noParentStage
  recommendExpression: 50000
  defaultValue: null
  valueType: NON_NEG_INT
  scope: !<RoleTypes>
    roleTypes: [DBA_SERVICE_SERVER]
  onDeps: []
  groups: ["application.yml"]
  visibility: READ_WRITE

- name: dbaservice.inceptor.limit.noParentTask
  recommendExpression: 1000000
  defaultValue: null
  valueType: NON_NEG_INT
  scope: !<RoleTypes>
    roleTypes: [DBA_SERVICE_SERVER]
  onDeps: []
  groups: ["application.yml"]
  visibility: READ_WRITE

- name: dbaservice.inceptor.limit.noParentLocalTask
  recommendExpression: 1000000
  defaultValue: null
  valueType: NON_NEG_INT
  scope: !<RoleTypes>
    roleTypes: [DBA_SERVICE_SERVER]
  onDeps: []
  groups: ["application.yml"]
  visibility: READ_WRITE

- name: dbaservice.inceptor.limit.expireTimeShort
  recommendExpression: 604800000
  defaultValue: null
  valueType: FLOAT
  scope: !<RoleTypes>
    roleTypes: [DBA_SERVICE_SERVER]
  onDeps: []
  groups: ["application.yml"]
  visibility: READ_WRITE

- name: dbaservice.inceptor.limit.expireTimeLong
  recommendExpression: 2592000000
  defaultValue: null
  valueType: FLOAT
  scope: !<RoleTypes>
    roleTypes: [DBA_SERVICE_SERVER]
  onDeps: []
  groups: ["application.yml"]
  visibility: READ_WRITE
