- name: server.container.limits.memory
  recommendExpression: -1
  defaultValue: null
  valueType: GB
  scope: !<RoleTypes>
    roleTypes: [AQUILA_SERVER]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: server.container.limits.cpu
  recommendExpression: 4
  defaultValue: null
  valueType: GB
  scope: !<RoleTypes>
    roleTypes: [AQUILA_SERVER]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: server.container.requests.memory
  recommendExpression: 1
  defaultValue: null
  valueType: GB
  scope: !<RoleTypes>
    roleTypes: [AQUILA_SERVER]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: server.container.requests.cpu
  recommendExpression: 0.5
  defaultValue: null
  valueType: GB
  scope: !<RoleTypes>
    roleTypes: [AQUILA_SERVER]
  onDeps: []
  groups: []
  visibility: READ_WRITE
