## AQUILA_TXSQL_SERVER
- name: txsql.data.dir
  recommendExpression: "/${service.sid}/txsql/data/"
  defaultValue: null
  valueType: ABSOLUTE_PATH
  scope: !<RoleTypes>
    roleTypes: [AQUILA_TXSQL_SERVER]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: txsql.mysql.rw.port
  recommendExpression: 8680
  defaultValue: null
  valueType: PORT
  scope: !<RoleTypes>
    roleTypes: [AQUILA_TXSQL_SERVER]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: txsql.binlog.port
  recommendExpression: 8681
  defaultValue: null
  valueType: PORT
  scope: !<RoleTypes>
    roleTypes: [AQUILA_TXSQL_SERVER]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: txsql.mysql.local.port
  recommendExpression: 8683
  defaultValue: null
  valueType: PORT
  scope: !<RoleTypes>
    roleTypes: [AQUILA_TXSQL_SERVER]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: txsql.binlogsvr.rpc.port
  recommendExpression: 8684
  defaultValue: null
  valueType: PORT
  scope: !<RoleTypes>
    roleTypes: [AQUILA_TXSQL_SERVER]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: txsql.paxos.port
  recommendExpression: 8685
  defaultValue: null
  valueType: PORT
  scope: !<RoleTypes>
    roleTypes: [GUARDIAN_TXSQL_SERVER]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: txsql.container.limits.memory
  recommendExpression: -1
  defaultValue: null
  valueType: GB
  scope: !<RoleTypes>
    roleTypes: [GUARDIAN_TXSQL_SERVER]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: txsql.container.limits.cpu
  recommendExpression: -1
  defaultValue: null
  valueType: NON_NEG_INT
  scope: !<RoleTypes>
    roleTypes: [GUARDIAN_TXSQL_SERVER]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: txsql.container.requests.memory
  recommendExpression: -1
  defaultValue: null
  valueType: GB
  scope: !<RoleTypes>
    roleTypes: [GUARDIAN_TXSQL_SERVER]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: txsql.container.requests.cpu
  recommendExpression: -1
  defaultValue: null
  valueType: NON_NEG_INT
  scope: !<RoleTypes>
    roleTypes: [GUARDIAN_TXSQL_SERVER]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: txsql.memory.ratio
  recommendExpression: -1
  defaultValue: null
  valueType: FLOAT
  scope: !<RoleTypes>
    roleTypes: [GUARDIAN_TXSQL_SERVER]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: txsql.root.password
  recommendExpression: ${(service['txsql.root.password']??)?then(service['txsql.root.password'],((.now?long * .now?long)%987654321)?c)}
  defaultValue: null
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: HIDDEN

## AQUILA_SERVER

- name: server.web.port
  recommendExpression: 8666
  defaultValue: 8080
  valueType: PORT
  scope: !<RoleTypes>
    roleTypes: [AQUILA_SERVER]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: server.api.swagger.enabled
  recommendExpression: false
  defaultValue: null
  valueType: BOOL
  scope: !<RoleTypes>
    roleTypes: [AQUILA_SERVER]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: server.log.app.level
  recommendExpression: INFO
  defaultValue: null
  valueType: STRING
  scope: !<RoleTypes>
    roleTypes: [AQUILA_SERVER]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: server.container.limits.memory
  recommendExpression: -1
  defaultValue: null
  valueType: FLOAT
  scope: !<RoleTypes>
    roleTypes: [AQUILA_SERVER]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: server.container.limits.cpu
  recommendExpression: 4
  defaultValue: null
  valueType: FLOAT
  scope: !<RoleTypes>
    roleTypes: [AQUILA_SERVER]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: server.container.requests.memory
  recommendExpression: 1
  defaultValue: null
  valueType: FLOAT
  scope: !<RoleTypes>
    roleTypes: [AQUILA_SERVER]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: server.container.requests.cpu
  recommendExpression: 0.5
  defaultValue: null
  valueType: FLOAT
  scope: !<RoleTypes>
    roleTypes: [AQUILA_SERVER]
  onDeps: []
  groups: []
  visibility: READ_WRITE

# AQUILA_AGENT

- name: agent.web.port
  recommendExpression: 8668
  defaultValue: 8080
  valueType: PORT
  scope: !<RoleTypes>
    roleTypes: [AQUILA_AGENT]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: agent.log.app.level
  recommendExpression: INFO
  defaultValue: null
  valueType: STRING
  scope: !<RoleTypes>
    roleTypes: [AQUILA_AGENT]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: agent.container.limits.memory
  recommendExpression: -1
  defaultValue: null
  valueType: FLOAT
  scope: !<RoleTypes>
    roleTypes: [AQUILA_AGENT]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: agent.container.limits.cpu
  recommendExpression: 4
  defaultValue: null
  valueType: FLOAT
  scope: !<RoleTypes>
    roleTypes: [AQUILA_AGENT]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: agent.container.requests.memory
  recommendExpression: 1
  defaultValue: null
  valueType: FLOAT
  scope: !<RoleTypes>
    roleTypes: [AQUILA_AGENT]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: agent.container.requests.cpu
  recommendExpression: 0.5
  defaultValue: null
  valueType: FLOAT
  scope: !<RoleTypes>
    roleTypes: [AQUILA_AGENT]
  onDeps: []
  groups: []
  visibility: READ_WRITE

# AQUILA_MANAGER_PROXY

- name: manager.proxy.web.port
  recommendExpression: 8672
  defaultValue: 8080
  valueType: PORT
  scope: !<RoleTypes>
    roleTypes: [AQUILA_MANAGER_PROXY]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: manager.proxy.log.app.level
  recommendExpression: INFO
  defaultValue: null
  valueType: STRING
  scope: !<RoleTypes>
    roleTypes: [AQUILA_MANAGER_PROXY]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: manager.proxy.container.limits.memory
  recommendExpression: -1
  defaultValue: null
  valueType: FLOAT
  scope: !<RoleTypes>
    roleTypes: [AQUILA_MANAGER_PROXY]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: manager.proxy.container.limits.cpu
  recommendExpression: 4
  defaultValue: null
  valueType: FLOAT
  scope: !<RoleTypes>
    roleTypes: [AQUILA_MANAGER_PROXY]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: manager.proxy.container.requests.memory
  recommendExpression: 1
  defaultValue: null
  valueType: FLOAT
  scope: !<RoleTypes>
    roleTypes: [AQUILA_MANAGER_PROXY]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: manager.proxy.container.requests.cpu
  recommendExpression: 0.5
  defaultValue: null
  valueType: FLOAT
  scope: !<RoleTypes>
    roleTypes: [AQUILA_MANAGER_PROXY]
  onDeps: []
  groups: []
  visibility: READ_WRITE


# AQUILA_NODE_EXPORTER

- name: node.exporter.web.port
  recommendExpression: 8670
  defaultValue: null
  valueType: PORT
  scope: !<RoleTypes>
    roleTypes: [NODE_EXPORTER]
  onDeps: []
  groups: []
  visibility: READ_WRITE


