---
name: TRANSPORTER
version: sophonweb-1.1-rc0
global: false
namePrefix: Transporter
friendlyName: Transwarp Data Transporter
dockerImage: "transwarp/tdt:sophonweb-1.1-rc0"
dependencies:
  - name: GUARDIAN
    minVersion: sophonweb-1.1-rc0
    maxVersion: sophonweb-1.1-rc0
    optional: true
  - name: HDFS
    minVersion: sophonweb-1.1-rc0
    maxVersion: sophonweb-1.1-rc0
    optional: false
  - name: INCEPTOR
    minVersion: sophonweb-1.1-rc0
    maxVersion: sophonweb-1.1-rc0
    optional: false
  - name: TXSQL
    minVersion: sophonweb-1.1-rc0
    maxVersion: sophonweb-1.1-rc0
    optional: false
roles:
- name: TDT_SERVER
  friendlyName: "Transporter Server"
  labelPrefix: "transporter-server"
  linkExpression: "http://${localhostname}:${service['tdt.server.port']}"  
  category: MASTER
  frontendOperations: ["Start", "Stop", "Delete", "Scaleout"]
  deleteOpCondition:
    deletable:
      number: 2
    reject:
      number: 1
  env:
  - name: TDT_CONF_DIR
    value: /etc/${service.sid}/conf
  mountPaths: []
  resources:
    limitsMemoryKey: tdt.container.limits.memory
    limitsCpuKey: tdt.container.limits.cpu
    requestsMemoryKey: tdt.container.requests.memory
    requestsCpuKey: tdt.container.requests.cpu
  summaryPolicy: ALL
  autoAssign:
  - advice: !<NumSeq> {"numSeq": [1]}
  suggestion:
  - criteria: !<Range> {"min": 1}
  validation:
  - criteria: !<Range> {"min": 1}
  operations:
  - type: Install
    directives:
    - directive: !<mkdirs>
        paths: ["/etc/${service.sid}/conf/hadoop"]
        mode: "755"
  - type: Config
    directives:
    - directive: !<link>
        action: Link
        from: "/etc/${dependencies.HDFS.sid}/conf/hdfs-site.xml"
        to: "/etc/${service.sid}/conf/hadoop/hdfs-site.xml"
    - directive: !<link>
        action: Link
        from: "/etc/${dependencies.HDFS.sid}/conf/core-site.xml"
        to: "/etc/${service.sid}/conf/hadoop/core-site.xml"
    - directive: !<resource>
        templateType: FreeMarker
        templatePath: "db.properties"
        targetPath: "/etc/${service.sid}/conf/db.properties"
        mode: "600"
stages:
  - type: Config
    taskGroups:
    - !<Create-Database>
      dbPrefix: tdt
      dbUserConfig: tdt.persistence.user.name
      dbPasswordConfig: tdt.persistence.password
      timeoutMinutes: 5
      summaryPolicy: SOME
    - !<Role>
      roleType: "TDT_SERVER"
      operation: Config
      summaryPolicy: SOME
      timeoutMinutes: 1
  - type: Bootstrap
    taskGroups:
    - !<Create-Database-in-Inceptor>
      summaryPolicy: ALL
      timeoutMinutes: 5
      dbNames: ["tdt", "tdt_results"]
  - type: PreUpgrade
    taskGroups:
    - !<DockerRunPreUpgrade>
      summaryPolicy: ALL
      timeoutMinutes: 10
      roleType: TDT_SERVER
      node: Any
  - type: PreRollback
    taskGroups:
    - !<DockerRunPreRollback>
      summaryPolicy: ALL
      timeoutMinutes: 10
      roleType: TDT_SERVER
      node: Any

product: Studio

firstWizardConfigs:
- tdt.server.host
- tdt.server.port
- tdt.persistence.user.name
- tdt.persistence.password
- tdt.task.live.time
- tdt.task.failure.retry.times
- tdt.task.failure.retry.period
- tdt.task.scavenger.check.period
- tdt.task.max.accept.size
- tdt.task.max.concurrence.size
- tdt.container.limits.memory
- tdt.container.limits.cpu
- tdt.container.requests.memory
- tdt.container.requests.cpu
- tdt.memory.ratio

principals:
- tdt
- hive

pages:
- roles
- configuration
- operation
- security

healthChecks:
- category: DAEMON_CHECK
  intervalSeconds: 10
  method: !<K8sPod> {}
