# tdt
- name: tdt.server.port
  recommendExpression: 8100
  defaultValue: null
  valueType: PORT
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: ["tdt-site.xml"]
  visibility: READ_WRITE
  
- name: tdt.persistence.user.name
  recommendExpression: tdtuser
  defaultValue: null
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: ["tdt-site.xml"]
  visibility: READ_WRITE

- name: tdt.persistence.password
  recommendExpression: password
  defaultValue: null
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: ["tdt-site.xml"]
  visibility: PASSWORD

- name: tdt.job.cleaning
  recommendExpression: true
  defaultValue: null
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: ["tdt-site.xml"]
  visibility: READ_WRITE

- name: tdt.job.remover.check.period
  recommendExpression: 30min
  defaultValue: null
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: ["tdt-site.xml"]
  visibility: READ_WRITE     
  
- name: tdt.job.max.accept.size
  recommendExpression: 10000
  defaultValue: null
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: ["tdt-site.xml"]
  visibility: READ_WRITE       
  
- name: tdt.job.max.concurrent.size
  recommendExpression: 100
  defaultValue: null
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: ["tdt-site.xml"]
  visibility: READ_WRITE

- name: tdt.thread.max.concurrent.size
  recommendExpression: 20
  defaultValue: null
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: ["tdt-site.xml"]
  visibility: READ_WRITE

- name: tdt.container.limits.memory
  recommendExpression: -1
  defaultValue: null
  valueType: FLOAT
  scope: !<RoleTypes>
    roleTypes: [TDT_SERVER]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: tdt.container.limits.cpu
  recommendExpression: -1
  defaultValue: null
  valueType: FLOAT
  scope: !<RoleTypes>
    roleTypes: [TDT_SERVER]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: tdt.container.requests.memory
  recommendExpression: -1
  defaultValue: null
  valueType: FLOAT
  scope: !<RoleTypes>
    roleTypes: [TDT_SERVER]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: tdt.container.requests.cpu
  recommendExpression: -1
  defaultValue: null
  valueType: FLOAT
  scope: !<RoleTypes>
    roleTypes: [TDT_SERVER]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: tdt.memory.ratio
  recommendExpression: 0.9
  defaultValue: null
  valueType: FLOAT
  scope: !<RoleTypes>
    roleTypes: [TDT_SERVER]
  onDeps: []
  groups: []
  visibility: READ_WRITE

# canal server
- name: canal.server.port
  recommendExpression: 11111
  defaultValue: null
  valueType: PORT
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: ["canal-server-site.xml"]
  visibility: READ_WRITE

- name: canal.zookeeper.flush.period
  recommendExpression: 1000
  defaultValue: 1000
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: ["canal-server-site.xml"]
  visibility: READ_WRITE

- name: canal.instance.memory.batch.mode
  recommendExpression: MEMSIZE
  defaultValue: MEMSIZE
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: ["canal-server-site.xml"]
  visibility: READ_WRITE

- name: canal.instance.memory.buffer.size
  recommendExpression: 1048576
  defaultValue: null
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: ["canal-server-site.xml"]
  visibility: READ_WRITE

- name: canal.instance.memory.buffer.memunit
  recommendExpression: 1024
  defaultValue: null
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: ["canal-server-site.xml"]
  visibility: READ_WRITE

- name: canal.instance.transaction.size
  recommendExpression: 2048
  defaultValue: null
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: ["canal-server-site.xml"]
  visibility: READ_WRITE

- name: canal.instance.fallbackIntervalInSeconds
  recommendExpression: 60
  defaultValue: null
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: ["canal-server-site.xml"]
  visibility: READ_WRITE

- name: canal.instance.detecting.sql
  recommendExpression: select 1 from dual
  defaultValue: null
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: ["canal-server-site.xml"]
  visibility: READ_WRITE

- name: canal.instance.detecting.interval.time
  recommendExpression: 3
  defaultValue: null
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: ["canal-server-site.xml"]
  visibility: READ_WRITE

- name: canal.instance.detecting.retry.threshold
  recommendExpression: 3
  defaultValue: null
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: ["canal-server-site.xml"]
  visibility: READ_WRITE

- name: canal.instance.detecting.heartbeatHaEnable
  recommendExpression: true
  defaultValue: null
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: ["canal-server-site.xml"]
  visibility: READ_WRITE

- name: canal.instance.network.sendBufferSize
  recommendExpression: 16384
  defaultValue: null
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: ["canal-server-site.xml"]
  visibility: READ_WRITE

- name: canal.instance.network.receiveBufferSize
  recommendExpression: 16384
  defaultValue: null
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: ["canal-server-site.xml"]
  visibility: READ_WRITE

- name: canal.instance.network.soTimeout
  recommendExpression: 30
  defaultValue: null
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: ["canal-server-site.xml"]
  visibility: READ_WRITE

- name: canal.instance.filter.druid.ddl
  recommendExpression: true
  defaultValue: null
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: ["canal-server-site.xml"]
  visibility: READ_WRITE

- name: canal.instance.filter.query.dcl
  recommendExpression: false
  defaultValue: null
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: ["canal-server-site.xml"]
  visibility: READ_WRITE

- name: canal.instance.filter.query.dml
  recommendExpression: false
  defaultValue: null
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: ["canal-server-site.xml"]
  visibility: READ_WRITE

- name: canal.instance.filter.query.ddl
  recommendExpression: false
  defaultValue: null
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: ["canal-server-site.xml"]
  visibility: READ_WRITE

- name: canal.instance.filter.table.error
  recommendExpression: false
  defaultValue: null
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: ["canal-server-site.xml"]
  visibility: READ_WRITE

- name: canal.instance.filter.rows
  recommendExpression: false
  defaultValue: null
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: ["canal-server-site.xml"]
  visibility: READ_WRITE

- name: canal.instance.filter.transaction.entry
  recommendExpression: false
  defaultValue: null
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: ["canal-server-site.xml"]
  visibility: READ_WRITE

- name: canal.instance.binlog.format
  recommendExpression: ROW,STATEMENT,MIXED
  defaultValue: null
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: ["canal-server-site.xml"]
  visibility: READ_WRITE

- name: canal.instance.binlog.image
  recommendExpression: FULL,MINIMAL,NOBLOB
  defaultValue: null
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: ["canal-server-site.xml"]
  visibility: READ_WRITE

- name: canal.instance.parser.parallel
  recommendExpression: true
  defaultValue: null
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: ["canal-server-site.xml"]
  visibility: READ_WRITE

- name: canal.instance.parser.parallelBufferSize
  recommendExpression: 256
  defaultValue: null
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: ["canal-server-site.xml"]
  visibility: READ_WRITE

- name: canal.instance.tsdb.enable
  recommendExpression: false
  defaultValue: null
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: ["canal-server-site.xml"]
  visibility: READ_WRITE

- name: canal-server.container.limits.memory
  recommendExpression: -1
  defaultValue: null
  valueType: FLOAT
  scope: !<RoleTypes>
    roleTypes: [CANAL_SERVER]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: canal-server.container.limits.cpu
  recommendExpression: -1
  defaultValue: null
  valueType: FLOAT
  scope: !<RoleTypes>
    roleTypes: [CANAL_SERVER]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: canal-server.container.requests.memory
  recommendExpression: -1
  defaultValue: null
  valueType: FLOAT
  scope: !<RoleTypes>
    roleTypes: [CANAL_SERVER]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: canal-server.container.requests.cpu
  recommendExpression: -1
  defaultValue: null
  valueType: FLOAT
  scope: !<RoleTypes>
    roleTypes: [CANAL_SERVER]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: canal-server.memory.ratio
  recommendExpression: 0.9
  defaultValue: null
  valueType: FLOAT
  scope: !<RoleTypes>
    roleTypes: [CANAL_SERVER]
  onDeps: []
  groups: []
  visibility: READ_WRITE

# canal client
- name: canal.client.batchSize
  recommendExpression: 1000
  defaultValue: null
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: ["canal-client-site.xml"]
  visibility: READ_WRITE

- name: canal.client.syncBatchSize
  recommendExpression: 1000
  defaultValue: null
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: ["canal-client-site.xml"]
  visibility: READ_WRITE

- name: canal.client.retry.times
  recommendExpression: 10
  defaultValue: null
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: ["canal-client-site.xml"]
  visibility: READ_WRITE

- name: canal.client.timeout
  recommendExpression: 3000
  defaultValue: null
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: ["canal-client-site.xml"]
  visibility: READ_WRITE

- name: canal.client.local.data.store
  recommendExpression: ${"/var/data/" + service['sid'] + "/canal-client"}
  defaultValue: null
  valueType: ABSOLUTE_PATH
  scope: !<RoleTypes>
    roleTypes: [CANAL_CLIENT]
  isNodeSpecific: true
  onDeps: []
  groups: ["canal-client-site.xml"]
  visibility: READ_WRITE

- name: canal-client.container.limits.memory
  recommendExpression: -1
  defaultValue: null
  valueType: FLOAT
  scope: !<RoleTypes>
    roleTypes: [CANAL_CLIENT]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: canal-client.container.limits.cpu
  recommendExpression: -1
  defaultValue: null
  valueType: FLOAT
  scope: !<RoleTypes>
    roleTypes: [CANAL_CLIENT]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: canal-client.container.requests.memory
  recommendExpression: -1
  defaultValue: null
  valueType: FLOAT
  scope: !<RoleTypes>
    roleTypes: [CANAL_CLIENT]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: canal-client.container.requests.cpu
  recommendExpression: -1
  defaultValue: null
  valueType: FLOAT
  scope: !<RoleTypes>
    roleTypes: [CANAL_CLIENT]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: canal-client.memory.ratio
  recommendExpression: 0.9
  defaultValue: null
  valueType: FLOAT
  scope: !<RoleTypes>
    roleTypes: [CANAL_CLIENT]
  onDeps: []
  groups: []
  visibility: READ_WRITE