# application-prod.properties
- name: javax.jdo.option.ConnectionUserName
  recommendExpression: mirroruser
  defaultValue: null
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: javax.jdo.option.ConnectionPassword
  recommendExpression: password
  defaultValue: null
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: PASSWORD

- name: mirror.userprofile.redis.port
  recommendExpression: 6379
  defaultValue: null
  valueType: PORT
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: READ_WRITE

#application.yml
- name: mirror.userprofile.port
  recommendExpression: 8888
  defaultValue: null
  valueType: PORT
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: READ_WRITE

#mirror.conf
- name: mirror.userprofile.hdfs.main.username
  recommendExpression: hdfs
  defaultValue: null
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: mirror.userprofile.inceptor.database.prod
  recommendExpression: mirror_prod
  defaultValue: null
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: mirror.userprofile.inceptor.database.check
  recommendExpression: mirror_check
  defaultValue: null
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: mirror.userprofile.inceptor.ldap.username
  recommendExpression: mirror
  defaultValue: null
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: mirror.userprofile.inceptor.ldap.password
  recommendExpression: password
  defaultValue: null
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: PASSWORD

- name: mirror.userprofile.container.limits.memory
  recommendExpression: -1
  defaultValue: null
  valueType: GB
  scope: !<RoleTypes>
    roleTypes: [MIRROR_USERPROFILE]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: mirror.userprofile.container.limits.cpu
  recommendExpression: -1
  defaultValue: null
  valueType: NON_NEG_INT
  scope: !<RoleTypes>
    roleTypes: [MIRROR_USERPROFILE]
  onDeps: []
  groups: []
  visibility: READ_WRITE


- name: mirror.userprofile.container.requests.memory
  recommendExpression: -1
  defaultValue: null
  valueType: GB
  scope: !<RoleTypes>
    roleTypes: [MIRROR_USERPROFILE]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: mirror.userprofile.container.requests.cpu
  recommendExpression: -1
  defaultValue: null
  valueType: NON_NEG_INT
  scope: !<RoleTypes>
    roleTypes: [MIRROR_USERPROFILE]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: redis.container.limits.memory
  recommendExpression: -1
  defaultValue: null
  valueType: GB
  scope: !<RoleTypes>
    roleTypes: [MIRROR_REDIS]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: redis.container.limits.cpu
  recommendExpression: -1
  defaultValue: null
  valueType: NON_NEG_INT
  scope: !<RoleTypes>
    roleTypes: [MIRROR_REDIS]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: redis.container.requests.memory
  recommendExpression: -1
  defaultValue: null
  valueType: GB
  scope: !<RoleTypes>
    roleTypes: [MIRROR_REDIS]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: redis.container.requests.cpu
  recommendExpression: -1
  defaultValue: null
  valueType: NON_NEG_INT
  scope: !<RoleTypes>
    roleTypes: [MIRROR_REDIS]
  onDeps: []
  groups: []
  visibility: READ_WRITE

