---
name: LADDER
version: argodb-1.2
global: false
namePrefix: Ladder
friendlyName: "Ladder"
dockerImage: "transwarp/argodb-ladder:argodb-1.2"
dependencies: []

roles:
##########
# Ladder #
##########
- name: LADDER_MASTER
  friendlyName: "Ladder Master"
  labelPrefix: "ladder-master"
  category: MASTER
  frontendOperations: ["Start", "Stop", "Delete", "Scaleout"]
  readinessProbe:
    probe: !<httpGet>
      path: /
      port: ${service['ladder.master.web.port']}
      scheme: HTTP
  summaryPolicy: SOME
  autoAssign:
  - advice: !<NumSeq> {"numSeq": [3]}
  suggestion:
  - criteria: !<Range> {"min": 3, "oddity": true}
  validation:
  - criteria: !<Range> {"min": 1}
  resources:
    limitsMemoryKey: ladder.master.container.limits.memory
    limitsCpuKey: ladder.master.container.limits.cpu
    requestsMemoryKey: ladder.master.container.requests.memory
    requestsCpuKey: ladder.master.container.requests.cpu
  nodeSpecificMounts:
  - configKey: ladder.master.journal.data_path
  - configKey: ladder.master.raft.data_path
  - configKey: ladder.master.localfs.data_path
  env:
  - name: LADDER_CONF_DIR
    value: /etc/${service.sid}/conf/ladder
  - name: LADDER_LOGS_DIR
    value: /var/log/${service.sid}/ladder
  deleteOpCondition:
    deletable:
      number: 3
      decommission: false
    reject:
      number: 2
  deleteOpCleanDirs:
    fromPath:
    - key: /var/transwarp/data/ladder/master_is_formated.identifier
      featureFile: master_is_formated.identifier
  mountPaths:
  - mountPath: /var/ladder_format
    hostPath: /var/transwarp/data/ladder
    name: format
  operations:
  - type: Install
    directives:
    - directive: !<mkdirs>
        paths: ["/etc/${service.sid}/conf/ladder"]
        mode: "755"
    - directive: !<mkdirs>
        paths: ["/var/transwarp/data/ladder"]
        mode: "755"
  - type: Config
    directives:
    - directive: !<resource>
        templateType: FreeMarker
        templatePath: "ladder/ladder-site.properties"
        targetPath: "/etc/${service.sid}/conf/ladder/ladder-site.properties"
        mode: "755"
    - directive: !<resource>
        templateType: Raw
        templatePath: "ladder/log4j.properties"
        targetPath: "/etc/${service.sid}/conf/ladder/log4j.properties"
        mode: "755"
    - directive: !<resource>
        templateType: FreeMarker
        templatePath: "ladder/workers"
        targetPath: "/etc/${service.sid}/conf/ladder/workers"
        mode: "755"

- name: LADDER_WORKER
  friendlyName: "Ladder Worker"
  labelPrefix: "ladder-worker"
  category: SLAVE
  frontendOperations: ["Start", "Stop", "Delete", "Scaleout"]
  readinessProbe:
    probe: !<httpGet>
      path: /
      port: ${service['ladder.worker.web.port']}
      scheme: HTTP
  summaryPolicy: MAJOR
  autoAssign:
  - advice: !<EachNode> {}
  suggestion:
  - criteria: !<Range> {"min": 3, "oddity": true}
  validation:
  - criteria: !<Range> {"min": 1}
  resources:
    limitsMemoryKey: ladder.worker.container.limits.memory
    limitsCpuKey: ladder.worker.container.limits.cpu
    requestsMemoryKey: ladder.worker.container.requests.memory
    requestsCpuKey: ladder.worker.container.requests.cpu
  nodeSpecificMounts:
  - configKey: ladder.worker.mem.data_path
  - configKey: ladder.worker.hdd.data_path
  env:
  - name: LADDER_CONF_DIR
    value: /etc/${service.sid}/conf/ladder
  - name: LADDER_LOGS_DIR
    value: /var/log/${service.sid}/ladder
  deleteOpCondition:
    deletable:
      number: 3
      decommission: false
    reject:
      number: 2
  deleteOpCleanDirs:
    fromPath:
    - key: /var/transwarp/data/ladder/worker_is_formated.identifier
      featureFile: worker_is_formated.identifier
  mountPaths:
  - mountPath: /var/ladder_format
    hostPath: /var/transwarp/data/ladder
    name: format
  operations:
  - type: Install
    directives:
    - directive: !<mkdirs>
        paths: ["/etc/${service.sid}/conf/ladder"]
        mode: "755"
    - directive: !<mkdirs>
        paths: ["/var/transwarp/data/ladder"]
        mode: "755"
    - directive: !<resource>
        templateType: FreeMarker
        templatePath: "ladder/ladder-mount.sh.ftl"
        targetPath: "/etc/${service.sid}/conf/ladder/ladder-mount.sh"
        mode: "755"
    - directive: !<shell>
        script: "bash -e /etc/${service.sid}/conf/ladder/ladder-mount.sh"
  - type: Config
    directives:
    - directive: !<resource>
        templateType: FreeMarker
        templatePath: "ladder/ladder-site.properties"
        targetPath: "/etc/${service.sid}/conf/ladder/ladder-site.properties"
        mode: "755"
    - directive: !<resource>
        templateType: Raw
        templatePath: "ladder/log4j.properties"
        targetPath: "/etc/${service.sid}/conf/ladder/log4j.properties"
        mode: "755"
    - directive: !<resource>
        templateType: FreeMarker
        templatePath: "ladder/workers"
        targetPath: "/etc/${service.sid}/conf/ladder/workers"
        mode: "755"

stages:
  - type: Config
    taskGroups:
    - !<Role>
      roleType: "LADDER_MASTER"
      operation: Config
      summaryPolicy: SOME
      timeoutMinutes: 1
    - !<Role>
      roleType: "LADDER_WORKER"
      operation: Config
      summaryPolicy: SOME
      timeoutMinutes: 1

firstWizardConfigs:
- ladder.master.rpc.port
- ladder.master.raft.port
- ladder.master.web.port
- ladder.master.container.limits.memory
- ladder.master.container.limits.cpu
- ladder.master.container.requests.memory
- ladder.master.container.requests.cpu
- ladder.master.journal.data_path
- ladder.master.raft.data_path
- ladder.master.localfs.data_path
- ladder.worker.web.port
- ladder.worker.container.limits.memory
- ladder.worker.container.limits.cpu
- ladder.worker.container.requests.memory
- ladder.worker.container.requests.cpu
- ladder.worker.mem.data_path
- ladder.worker.hdd.data_path
- ladder.worker.mem.size
- ladder.worker.tieredstore.level1.dirs.quota

dashboardMetrics: []

pages:
- summary
- roles
- configuration
- operation
- resource_allocation

healthChecks:
- category: DAEMON_CHECK
  intervalSeconds: 5
  method: !<K8sPod> {}

