- name: dbaservice.container.limits.memory
  recommendExpression: -1
  defaultValue: null
  valueType: FLOAT
  scope: !<RoleTypes>
    roleTypes: [DBA_SERVICE_SERVER]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: dbaservice.container.limits.cpu
  recommendExpression: -1
  defaultValue: null
  valueType: FLOAT
  scope: !<RoleTypes>
    roleTypes: [DBA_SERVICE_SERVER]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: dbaservice.container.requests.memory
  recommendExpression: -1
  defaultValue: null
  valueType: FLOAT
  scope: !<RoleTypes>
    roleTypes: [DBA_SERVICE_SERVER]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: dbaservice.container.requests.cpu
  recommendExpression: -1
  defaultValue: null
  valueType: FLOAT
  scope: !<RoleTypes>
    roleTypes: [DBA_SERVICE_SERVER]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: dbaservice.ui.port
  recommendExpression: 4040
  defaultValue: null
  valueType: PORT
  scope: !<RoleTypes>
    roleTypes: [DBA_SERVICE_SERVER]
  onDeps: []
  groups: ["application.yml"]
  visibility: READ_WRITE

- name: dbaservice.message.port
  recommendExpression: 60606
  defaultValue: null
  valueType: PORT
  scope: !<RoleTypes>
    roleTypes: [DBA_SERVICE_SERVER]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: dbaservice.request.port
  recommendExpression: 60607
  defaultValue: null
  valueType: PORT
  scope: !<RoleTypes>
    roleTypes: [DBA_SERVICE_SERVER]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: dbaservice.aiops.ui.port
  recommendExpression: 8008
  defaultValue: null
  valueType: PORT
  scope: !<RoleTypes>
    roleTypes: [DBA_SERVICE_SERVER]
  onDeps: []
  groups: ["application.yml", "aiops.yml"]
  visibility: READ_WRITE

- name: dbaservice.security.enabled
  recommendExpression: false
  defaultValue: false
  valueType: BOOL
  scope: !<RoleTypes>
    roleTypes: [DBA_SERVICE_SERVER]
  onDeps: []
  groups: ["application.yml"]
  visibility: READ_WRITE

- name: dbaservice.server.tls.enabled
  recommendExpression: true
  defaultValue: true
  valueType: BOOL
  scope: !<RoleTypes>
    roleTypes: [DBA_SERVICE_SERVER]
  onDeps: []
  groups: ["application.yml", "aiops.yml"]
  visibility: READ_WRITE

- name: dbaservice.inceptor.limit.status
  recommendExpression: 10000
  defaultValue: null
  valueType: NON_NEG_INT
  scope: !<RoleTypes>
    roleTypes: [DBA_SERVICE_SERVER]
  onDeps: []
  groups: ["application.yml"]
  visibility: READ_WRITE

- name: dbaservice.inceptor.limit.session
  recommendExpression: 10000
  defaultValue: null
  valueType: NON_NEG_INT
  scope: !<RoleTypes>
    roleTypes: [DBA_SERVICE_SERVER]
  onDeps: []
  groups: ["application.yml"]
  visibility: READ_WRITE

- name: dbaservice.inceptor.limit.completeSql
  recommendExpression: 5000
  defaultValue: null
  valueType: NON_NEG_INT
  scope: !<RoleTypes>
    roleTypes: [DBA_SERVICE_SERVER]
  onDeps: []
  groups: ["application.yml"]
  visibility: READ_WRITE

- name: dbaservice.inceptor.limit.incompleteSql
  recommendExpression: 10000
  defaultValue: null
  valueType: NON_NEG_INT
  scope: !<RoleTypes>
    roleTypes: [DBA_SERVICE_SERVER]
  onDeps: []
  groups: ["application.yml"]
  visibility: READ_WRITE

- name: dbaservice.inceptor.limit.errorSql
  recommendExpression: 10000
  defaultValue: null
  valueType: NON_NEG_INT
  scope: !<RoleTypes>
    roleTypes: [DBA_SERVICE_SERVER]
  onDeps: []
  groups: ["application.yml"]
  visibility: READ_WRITE

- name: dbaservice.inceptor.limit.incompleteJob
  recommendExpression: 20000
  defaultValue: null
  valueType: NON_NEG_INT
  scope: !<RoleTypes>
    roleTypes: [DBA_SERVICE_SERVER]
  onDeps: []
  groups: ["application.yml"]
  visibility: READ_WRITE

- name: dbaservice.inceptor.limit.incompleteStage
  recommendExpression: 50000
  defaultValue: null
  valueType: NON_NEG_INT
  scope: !<RoleTypes>
    roleTypes: [DBA_SERVICE_SERVER]
  onDeps: []
  groups: ["application.yml"]
  visibility: READ_WRITE

- name: dbaservice.inceptor.limit.incompleteTask
  recommendExpression: 1000000
  defaultValue: null
  valueType: NON_NEG_INT
  scope: !<RoleTypes>
    roleTypes: [DBA_SERVICE_SERVER]
  onDeps: []
  groups: ["application.yml"]
  visibility: READ_WRITE

- name: dbaservice.inceptor.limit.incompleteLocalTask
  recommendExpression: 1000000
  defaultValue: null
  valueType: NON_NEG_INT
  scope: !<RoleTypes>
    roleTypes: [DBA_SERVICE_SERVER]
  onDeps: []
  groups: ["application.yml"]
  visibility: READ_WRITE

- name: dbaservice.inceptor.limit.task
  recommendExpression: 5000000
  defaultValue: null
  valueType: NON_NEG_INT
  scope: !<RoleTypes>
    roleTypes: [DBA_SERVICE_SERVER]
  onDeps: []
  groups: ["application.yml"]
  visibility: READ_WRITE

- name: dbaservice.inceptor.limit.noParentJob
  recommendExpression: 20000
  defaultValue: null
  valueType: NON_NEG_INT
  scope: !<RoleTypes>
    roleTypes: [DBA_SERVICE_SERVER]
  onDeps: []
  groups: ["application.yml"]
  visibility: READ_WRITE

- name: dbaservice.inceptor.limit.noParentStage
  recommendExpression: 50000
  defaultValue: null
  valueType: NON_NEG_INT
  scope: !<RoleTypes>
    roleTypes: [DBA_SERVICE_SERVER]
  onDeps: []
  groups: ["application.yml"]
  visibility: READ_WRITE

- name: dbaservice.inceptor.limit.noParentTask
  recommendExpression: 1000000
  defaultValue: null
  valueType: NON_NEG_INT
  scope: !<RoleTypes>
    roleTypes: [DBA_SERVICE_SERVER]
  onDeps: []
  groups: ["application.yml"]
  visibility: READ_WRITE

- name: dbaservice.inceptor.limit.noParentLocalTask
  recommendExpression: 1000000
  defaultValue: null
  valueType: NON_NEG_INT
  scope: !<RoleTypes>
    roleTypes: [DBA_SERVICE_SERVER]
  onDeps: []
  groups: ["application.yml"]
  visibility: READ_WRITE

- name: dbaservice.inceptor.limit.expireTimeShort
  recommendExpression: 604800000
  defaultValue: null
  valueType: FLOAT
  scope: !<RoleTypes>
    roleTypes: [DBA_SERVICE_SERVER]
  onDeps: []
  groups: ["application.yml"]
  visibility: READ_WRITE

- name: dbaservice.inceptor.limit.expireTimeLong
  recommendExpression: 2592000000
  defaultValue: null
  valueType: FLOAT
  scope: !<RoleTypes>
    roleTypes: [DBA_SERVICE_SERVER]
  onDeps: []
  groups: ["application.yml"]
  visibility: READ_WRITE

- name: dbaservice.persistence.enabled
  recommendExpression: true
  defaultValue: true
  valueType: BOOL
  scope: !<RoleTypes>
    roleTypes: [DBA_SERVICE_SERVER]
  onDeps: []
  groups: ["application.yml"]
  visibility: READ_WRITE

- name: dbaservice.persistence.datadir
  recommendExpression: |
    <#function localDir suffix>
      <#if rcmdMounts?size == 0>
        <#return suffix>
      <#else>
        <#return rcmdMounts?sort?first + suffix>
      </#if>
    </#function>
    ${localDir("/dbaservice/" + service['sid'])}
  defaultValue: null
  valueType: STRING
  isNodeSpecific: true
  scope: !<RoleTypes>
    roleTypes: [DBA_SERVICE_SERVER]
  onDeps: []
  groups: ["application.yml"]
  visibility: READ_WRITE

- name: dbaservice.persistence.db.username
  recommendExpression: admin
  defaultValue: null
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: ["application.yml"]
  visibility: READ_WRITE

- name: dbaservice.persistence.db.password
  recommendExpression: password
  defaultValue: null
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: ["application.yml"]
  visibility: PASSWORD

- name: dbaservice.persistence.db.max.filesize
  recommendExpression: 100GB
  defaultValue: null
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: ["application.yml"]
  visibility: READ_WRITE

- name: dbaservice.persistence.inceptor.saveTasks
  recommendExpression: true
  defaultValue: true
  valueType: BOOL
  scope: !<RoleTypes>
    roleTypes: [DBA_SERVICE_SERVER]
  onDeps: []
  groups: ["application.yml"]
  visibility: READ_WRITE

- name: dbaservice.persistence.inceptor.saveExecutors
  recommendExpression: false
  defaultValue: false
  valueType: BOOL
  scope: !<RoleTypes>
    roleTypes: [DBA_SERVICE_SERVER]
  onDeps: []
  groups: ["application.yml"]
  visibility: READ_WRITE

- name: dbaservice.persistence.inceptor.updateExecutorBeforeSaving
  recommendExpression: false
  defaultValue: false
  valueType: BOOL
  scope: !<RoleTypes>
    roleTypes: [DBA_SERVICE_SERVER]
  onDeps: []
  groups: ["application.yml"]
  visibility: READ_WRITE

- name: dbaservice.persistence.inceptor.limit.sql
  recommendExpression: 100000
  defaultValue: null
  valueType: FLOAT
  scope: !<RoleTypes>
    roleTypes: [DBA_SERVICE_SERVER]
  onDeps: []
  groups: ["application.yml"]
  visibility: READ_WRITE

- name: dbaservice.persistence.inceptor.limit.server
  recommendExpression: 10000
  defaultValue: null
  valueType: FLOAT
  scope: !<RoleTypes>
    roleTypes: [DBA_SERVICE_SERVER]
  onDeps: []
  groups: ["application.yml"]
  visibility: READ_WRITE

- name: dbaservice.persistence.inceptor.limit.executor
  recommendExpression: 10000
  defaultValue: null
  valueType: FLOAT
  scope: !<RoleTypes>
    roleTypes: [DBA_SERVICE_SERVER]
  onDeps: []
  groups: ["application.yml"]
  visibility: READ_WRITE

- name: EXTRA_DBASERVICE_OPTS
  recommendExpression: ""
  defaultValue: ""
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: EXTRA_AIOPS_OPTS
  recommendExpression: ""
  defaultValue: ""
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: READ_WRITE