apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: sophon-web
  name: sophon-web
rules:
- apiGroups:
  - ""
  resources:
  - deployments
  verbs:
  - get
  - list
  - create
  - delete
- apiGroups:
  - ""
  resources:
  - pod
  verbs:
  - watch
  - get
  - list
  - create
  - update
  - delete
- apiGroups:
  - ""
  resources:
  - svc
  verbs:
  - get
  - list
  - create
  - delete
- apiGroups:
  - ""
  resources:
  - event
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - configmap
  verbs:
  - get
  - list
  - create
  - delete

