---
- name: prometheus.data.dir
  recommendExpression: |
    <#function localDir suffix>
      <#if rcmdMounts?size == 0>
        <#return suffix>
      <#else>
        <#local dir = rcmdMounts[0] + suffix>
        <#return dir>
      </#if>
    </#function>
    ${localDir("/" + service['sid'] + "/prometheus-data")}
  defaultValue: file:///prometheus-data
  valueType: STRING
  isNodeSpecific: true
  scope: !<RoleTypes>
    roleTypes: [MONITOR_PROMETHEUS]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: prometheus.port
  recommendExpression: 9090
  defaultValue: null
  valueType: PORT
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: prometheus.container.limits.memory
  recommendExpression: -1
  defaultValue: null
  valueType: GB
  scope: !<RoleTypes>
    roleTypes: [MONITOR_PROMETHEUS]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: prometheus.container.limits.cpu
  recommendExpression: -1
  defaultValue: null
  valueType: NON_NEG_INT
  scope: !<RoleTypes>
    roleTypes: [MONITOR_PROMETHEUS]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: prometheus.container.requests.memory
  recommendExpression: -1
  defaultValue: null
  valueType: GB
  scope: !<RoleTypes>
    roleTypes: [MONITOR_PROMETHEUS]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: prometheus.container.requests.cpu
  recommendExpression: -1
  defaultValue: null
  valueType: NON_NEG_INT
  scope: !<RoleTypes>
    roleTypes: [MONITOR_PROMETHEUS]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: nodeexporter.port
  recommendExpression: 9101
  defaultValue: null
  valueType: PORT
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: nodeexporter.container.limits.memory
  recommendExpression: -1
  defaultValue: null
  valueType: GB
  scope: !<RoleTypes>
    roleTypes: [MONITOR_NODEEXPORTER]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: nodeexporter.container.limits.cpu
  recommendExpression: -1
  defaultValue: null
  valueType: FLOAT
  scope: !<RoleTypes>
    roleTypes: [MONITOR_NODEEXPORTER]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: nodeexporter.container.requests.memory
  recommendExpression: -1
  defaultValue: null
  valueType: GB
  scope: !<RoleTypes>
    roleTypes: [MONITOR_NODEEXPORTER]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: nodeexporter.container.requests.cpu
  recommendExpression: -1
  defaultValue: null
  valueType: FLOAT
  scope: !<RoleTypes>
    roleTypes: [MONITOR_NODEEXPORTER]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: kubemetrics.port
  recommendExpression: 9080
  defaultValue: null
  valueType: PORT
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: kubemetrics.container.limits.memory
  recommendExpression: -1
  defaultValue: null
  valueType: GB
  scope: !<RoleTypes>
    roleTypes: [MONITOR_KUBE_METRICS]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: kubemetrics.container.limits.cpu
  recommendExpression: -1
  defaultValue: null
  valueType: FLOAT
  scope: !<RoleTypes>
    roleTypes: [MONITOR_KUBE_METRICS]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: kubemetrics.container.requests.memory
  recommendExpression: -1
  defaultValue: null
  valueType: GB
  scope: !<RoleTypes>
    roleTypes: [MONITOR_KUBE_METRICS]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: kubemetrics.container.requests.cpu
  recommendExpression: -1
  defaultValue: null
  valueType: FLOAT
  scope: !<RoleTypes>
    roleTypes: [MONITOR_KUBE_METRICS]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: grafana.port
  recommendExpression: 3000
  defaultValue: null
  valueType: PORT
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: grafana.container.limits.memory
  recommendExpression: -1
  defaultValue: null
  valueType: GB
  scope: !<RoleTypes>
    roleTypes: [MONITOR_GRAFANA]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: grafana.container.limits.cpu
  recommendExpression: -1
  defaultValue: null
  valueType: FLOAT
  scope: !<RoleTypes>
    roleTypes: [MONITOR_GRAFANA]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: grafana.container.requests.memory
  recommendExpression: -1
  defaultValue: null
  valueType: GB
  scope: !<RoleTypes>
    roleTypes: [MONITOR_GRAFANA]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: grafana.container.requests.cpu
  recommendExpression: -1
  defaultValue: null
  valueType: FLOAT
  scope: !<RoleTypes>
    roleTypes: [MONITOR_GRAFANA]
  onDeps: []
  groups: []
  visibility: READ_WRITE
