---
name: GUARDIAN
version: sophonweb-1.0.2-rc2
global: true
namePrefix: Guardian
friendlyName: Guardian
dependencies: []
roles:
- name: GUARDIAN_APACHEDS
  friendlyName: "Guardian ApacheDS"
  labelPrefix: "guardian-apacheds"
  category: MASTER
  frontendOperations: ["Start", "Stop", "Delete", "Move", "Scaleout"]
  deleteOpCondition:
    movable:
      number: 2
  summaryPolicy: SOME
  dockerImage: "transwarp/apacheds:sophonweb-1.0.2-rc2"
  autoAssign:
  - advice: !<NumSeq> {"numSeq": [2, 1]}
  suggestion:
  - criteria: !<Range> {"min": 1}
  validation:
  - criteria: !<Range> {"min": 1}
  env:
  - name: GUARDIAN_CONF_DIR
    value: /etc/${service.sid}/conf
  - name: GUARDIAN_LOG_FILE
    value: guardian-apacheds.log
  mountPaths:
  - mountPath: ${service['guardian.apacheds.data.dir']}
    hostPath: ${service['guardian.apacheds.data.dir']}
    name: srv
  operations:
  - type: Install
    directives:
    - directive: !<mkdirs>
        paths: ["${service['guardian.apacheds.data.dir']}"]
        mode: "755"
- name: GUARDIAN_SERVER
  friendlyName: "Guardian Server"
  labelPrefix: "guardian-server"
  category: MASTER
  frontendOperations: ["Start", "Stop", "Delete", "Move", "Scaleout"]
  deleteOpCondition:
    deletable:
      number: 2
    movable:
      number: 1
  linkExpression: <#if service['guardian.server.tls.enabled'] = "true">https<#else>http</#if>://${localhostname}:${service['guardian.server.port']}
  summaryPolicy: SOME
  dockerImage: "transwarp/guardian:sophonweb-1.0.2-rc2"
  autoAssign:
  - advice: !<NumSeq> {"numSeq": [2, 1]}
  suggestion:
  - criteria: !<Range> {"min": 1}
  validation:
  - criteria: !<Range> {"min": 1}
  env:
  - name: GUARDIAN_CONF_DIR
    value: /etc/${service.sid}/conf
  - name: GUARDIAN_LOG_FILE
    value: guardian-server.log
  mountPaths:
  - mountPath: /srv/guardian
    hostPath: /srv/guardian
    name: srv
  operations:
  - type: Install
    directives:
    - directive: !<shell>
        script: "docker run -v /srv/guardian:/srv/guardian --net=host ${dependencies.TOS.roles['TOS_REGISTRY'][0].hostname}:${dependencies.TOS['tos.registry.port']}/transwarp/guardian-gencerts:sophonweb-1.0.2-rc2 entry.sh"

jobs:
  - type: Init
    stages:
    - Install
    - GenKeystore
    - Config
    - Start
    - GenKeytab
  - type: Start
    stages:
    - Start
    - GenKeytab
  - type: Config
    stages:
    - GenKeystore
    - Config

firstWizardConfigs:
- guardian.server.port
- guardian.apacheds.ldap.port
- guardian.apacheds.kdc.port
- guardian.apacheds.data.dir
- guardian.client.cache.enabled
- guardian.ds.realm
- guardian.ds.domain

principals:
- guardian/guardian

healthChecks:
- category: DAEMON_CHECK
  intervalSeconds: 15
  method: !<K8sPod> {}
- category: VITAL_SIGN_CHECK
  intervalSeconds: 20
  method: !<Builtin> {}
