- name: graph.data.dirs
  recommendExpression: |
    <#function localDir suffix>
      <#if rcmdMounts?size == 0>
        <#return suffix>
      <#else>
        <#local dirs = []>
        <#list rcmdMounts?sort as mnt>
         <#local dirs = dirs + [mnt + suffix]>
        </#list>
        <#return dirs?join(",")>
      </#if>
    </#function>
    ${localDir("/stellardb/graph/" + service['sid'])}
  isNodeSpecific: true
  defaultValue: null
  valueType: STRING
  scope: !<RoleTypes> {roleTypes: [STELLARDB_WORKER]}
  onDeps: []
  groups: ["graphconf.xml"]
  visibility: READ_WRITE
- name: graph.raft.dirs
  recommendExpression: |
    <#function localDir suffix>
      <#if rcmdMounts?size == 0>
        <#return suffix>
      <#else>
        <#local dirs = []>
        <#list rcmdMounts?sort as mnt>
         <#local dirs = dirs + [mnt + suffix]>
        </#list>
        <#return dirs?join(",")>
      </#if>
    </#function>
    ${localDir("/stellardb/raft/" + service['sid'])}
  isNodeSpecific: true
  defaultValue: null
  valueType: STRING
  scope: !<RoleTypes> {roleTypes: [STELLARDB_WORKER]}
  onDeps: []
  groups: ["graphconf.xml"]
  visibility: READ_WRITE
- name: graph.zk.quorum
  recommendExpression: |
    <#compress>
    <#assign zookeeper=dependencies.ZOOKEEPER quorum=[]>
    <#list zookeeper.roles.ZOOKEEPER as role>
        <#assign quorum += [role.hostname + ":" + zookeeper["zookeeper.client.port"]]>
    </#list>
    ${quorum?join(",")}
    </#compress>
  defaultValue: null
  valueType: STRING
  scope: !<RoleTypes> {roleTypes: [STELLARDB_WORKER]}
  onDeps: ['ZOOKEEPER']
  groups: ["graphconf.xml"]
  visibility: READ_WRITE
- name: graph.master.port
  recommendExpression: 30909
  defaultValue: null
  valueType: HOST_PORT
  scope: !<RoleTypes> {roleTypes: [STELLARDB_MASTER]}
  onDeps: []
  groups: ["graphconf.xml"]
  visibility: READ_WRITE
- name: graph.master.ui.port
  recommendExpression: 50088
  defaultValue: null
  valueType: HOST_PORT
  scope: !<RoleTypes> {roleTypes: [STELLARDB_MASTER]}
  onDeps: []
  groups: ["graphconf.xml"]
  visibility: READ_WRITE
- name: graph.worker.port
  recommendExpression: 30815
  defaultValue: null
  valueType: HOST_PORT
  scope: !<RoleTypes> {roleTypes: [STELLARDB_WORKER]}
  onDeps: []
  groups: ["graphconf.xml"]
  visibility: READ_WRITE
- name: graph.worker.ui.port
  recommendExpression: 50089
  defaultValue: null
  valueType: HOST_PORT
  scope: !<RoleTypes> {roleTypes: [STELLARDB_WORKER]}
  onDeps: []
  groups: ["graphconf.xml"]
  visibility: READ_WRITE
- name: graph.zk.base_path
  recommendExpression: "/graph"
  defaultValue: null
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: ["graphconf.xml"]
  visibility: READ_WRITE
- name: graph.raft.server.port
  recommendExpression: 1998
  defaultValue: null
  valueType: HOST_PORT
  scope: !<RoleTypes> {roleTypes: [STELLARDB_WORKER]}
  onDeps: []
  groups: ["graphconf.xml"]
  visibility: READ_WRITE
- name: graph.cypher.jdbc.url
  recommendExpression: jdbc:hive2://localhost:10000/default
  defaultValue: null
  valueType: STRING
  scope: !<RoleTypes> {roleTypes: [STELLARDB_WORKER]}
  onDeps: []
  groups: ["graphconf.xml"]
  visibility: READ_WRITE
