##########
# Ladder #
##########
- name: ladder.master.raft.port
  recommendExpression: 6001
  defaultValue: null
  valueType: NON_NEG_INT
  scope: !<RoleTypes> {roleTypes: [LADDER_MASTER, LADDER_WORKER]}
  onDeps: []
  groups: ["ladder-site.properties"]
  visibility: READ_WRITE

- name: ladder.master.rpc.port
  recommendExpression: 19998
  defaultValue: null
  valueType: NON_NEG_INT
  scope: !<RoleTypes> {roleTypes: [LADDER_MASTER, LADDER_WORKER]}
  onDeps: []
  groups: ["ladder-site.properties"]
  visibility: READ_WRITE

- name: ladder.master.web.port
  recommendExpression: 19999
  defaultValue: null
  valueType: NON_NEG_INT
  scope: !<RoleTypes> {roleTypes: [LADDER_MASTER, LADDER_WORKER]}
  onDeps: []
  groups: ["ladder-site.properties"]
  visibility: READ_WRITE

- name: ladder.master.container.limits.memory
  recommendExpression: -1
  defaultValue: null
  valueType: GB
  scope: !<RoleTypes> {roleTypes: [LADDER_MASTER, LADDER_WORKER]}
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: ladder.master.container.limits.cpu
  recommendExpression: -1
  defaultValue: null
  valueType: NON_NEG_INT
  scope: !<RoleTypes> {roleTypes: [LADDER_MASTER, LADDER_WORKER]}
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: ladder.master.container.requests.memory
  recommendExpression: -1
  defaultValue: null
  valueType: GB
  scope: !<RoleTypes> {roleTypes: [LADDER_MASTER, LADDER_WORKER]}
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: ladder.master.container.requests.cpu
  recommendExpression: -1
  defaultValue: null
  valueType: NON_NEG_INT
  scope: !<RoleTypes> {roleTypes: [LADDER_MASTER, LADDER_WORKER]}
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: ladder.master.journal.data_path
  recommendExpression: |
    <#assign sorted = rcmdMounts?sort>
    <#if sorted?size == 0>
    /ladder/journal
    <#elseif sorted?size == 1>
    ${sorted?first}/ladder/journal
    <#else>
    ${sorted[0]}/ladder/journal
    </#if>
  defaultValue: null
  valueType: STRING
  isNodeSpecific: true
  scope: !<RoleTypes> {roleTypes: [LADDER_MASTER, LADDER_WORKER]}
  onDeps: []
  groups: ["ladder-site.properties"]
  visibility: READ_WRITE

- name: ladder.master.raft.data_path
  recommendExpression: |
    <#assign sorted = rcmdMounts?sort>
    <#if sorted?size == 0>
    /ladder/journal
    <#elseif sorted?size == 1>
    ${sorted?first}/ladder/raftlog
    <#else>
    ${sorted[0]}/ladder/raftlog
    </#if>
  defaultValue: null
  valueType: STRING
  isNodeSpecific: true
  scope: !<RoleTypes> {roleTypes: [LADDER_MASTER, LADDER_WORKER]}
  onDeps: []
  groups: ["ladder-site.properties"]
  visibility: READ_WRITE

- name: ladder.master.localfs.data_path
  recommendExpression: |
    /tmp/ladder/localfs
  defaultValue: null
  valueType: STRING
  isNodeSpecific: false
  scope: !<RoleTypes> {roleTypes: [LADDER_MASTER, LADDER_WORKER]}
  onDeps: []
  groups: ["ladder-site.properties"]
  visibility: READ_WRITE

#- name: ladder.worker.port
#  recommendExpression: 29998
#  defaultValue: null
#  valueType: NON_NEG_INT
#  scope: !<RoleTypes> {roleTypes: [LADDER_MASTER, LADDER_WORKER]}
#  onDeps: []
#  groups: ["ladder-site.properties"]
#  visibility: READ_WRITE

#- name: ladder.worker.data.port
#  recommendExpression: 29999
#  defaultValue: null
#  valueType: NON_NEG_INT
#  scope: !<RoleTypes> {roleTypes: [LADDER_MASTER, LADDER_WORKER]}
#  onDeps: []
#  groups: ["ladder-site.properties"]
#  visibility: READ_WRITE

- name: ladder.worker.web.port
  recommendExpression: 30000
  defaultValue: null
  valueType: NON_NEG_INT
  scope: !<RoleTypes> {roleTypes: [LADDER_MASTER, LADDER_WORKER]}
  onDeps: []
  groups: ["ladder-site.properties"]
  visibility: READ_WRITE

- name: ladder.worker.container.limits.memory
  recommendExpression: -1
  defaultValue: null
  valueType: GB
  scope: !<RoleTypes> {roleTypes: [LADDER_MASTER, LADDER_WORKER]}
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: ladder.worker.container.limits.cpu
  recommendExpression: -1
  defaultValue: null
  valueType: NON_NEG_INT
  scope: !<RoleTypes> {roleTypes: [LADDER_MASTER, LADDER_WORKER]}
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: ladder.worker.container.requests.memory
  recommendExpression: -1
  defaultValue: null
  valueType: GB
  scope: !<RoleTypes> {roleTypes: [LADDER_MASTER, LADDER_WORKER]}
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: ladder.worker.container.requests.cpu
  recommendExpression: -1
  defaultValue: null
  valueType: NON_NEG_INT
  scope: !<RoleTypes> {roleTypes: [LADDER_MASTER, LADDER_WORKER]}
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: ladder.worker.mem.data_path
  recommendExpression: |
    /mnt/laddermemdisk${service.sid}
  defaultValue: null
  valueType: STRING
  isNodeSpecific: true
  scope: !<RoleTypes> {roleTypes: [LADDER_MASTER, LADDER_WORKER]}
  onDeps: []
  groups: ["ladder-site.properties"]
  visibility: READ_WRITE

- name: ladder.worker.hdd.data_path
  recommendExpression: |
    <#function localDir suffix>
      <#if rcmdMounts?size == 0>
        <#return suffix>
      <#else>
        <#local dirs = []>
        <#list rcmdMounts?sort as mnt>
         <#local dirs = dirs + [mnt + suffix]>
        </#list>
        <#return dirs?join(",")>
      </#if>
    </#function>
    ${localDir("/ladder/data")}
  defaultValue: null
  valueType: STRING
  isNodeSpecific: true
  scope: !<RoleTypes> {roleTypes: [LADDER_MASTER, LADDER_WORKER]}
  onDeps: []
  groups: ["ladder-site.properties"]
  visibility: READ_WRITE

- name: ladder.worker.mem.size
  recommendExpression: |
    4GB
  defaultValue: null
  valueType: STRING
  isNodeSpecific: true
  scope: !<RoleTypes> {roleTypes: [LADDER_MASTER, LADDER_WORKER]}
  onDeps: []
  groups: ["ladder-site.properties"]
  visibility: READ_WRITE

- name: ladder.worker.tieredstore.level1.dirs.quota
  recommendExpression: |
    100GB
  defaultValue: null
  valueType: STRING
  isNodeSpecific: true
  scope: !<RoleTypes> {roleTypes: [LADDER_MASTER, LADDER_WORKER]}
  onDeps: []
  groups: ["ladder-site.properties"]
  visibility: READ_WRITE