#dashboard
- name: codis.dashboard.container.limits.memory
  recommendExpression: -1
  defaultValue: null
  valueType: FLOAT
  scope: !<RoleTypes>
    roleTypes: [CODIS_DASHBOARD]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: codis.dashboard.container.limits.cpu
  recommendExpression: -1
  defaultValue: null
  valueType: FLOAT
  scope: !<RoleTypes>
    roleTypes: [CODIS_DASHBOARD]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: codis.dashboard.container.requests.memory
  recommendExpression: -1
  defaultValue: null
  valueType: FLOAT
  scope: !<RoleTypes>
    roleTypes: [CODIS_DASHBOARD]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: codis.dashboard.container.requests.cpu
  recommendExpression: -1
  defaultValue: null
  valueType: FLOAT
  scope: !<RoleTypes>
    roleTypes: [CODIS_DASHBOARD]
  onDeps: []
  groups: []
  visibility: READ_WRITE

#proxy
- name: codis.proxy.container.limits.memory
  recommendExpression: -1
  defaultValue: null
  valueType: FLOAT
  scope: !<RoleTypes>
    roleTypes: [CODIS_PROXY]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: codis.proxy.container.limits.cpu
  recommendExpression: -1
  defaultValue: null
  valueType: FLOAT
  scope: !<RoleTypes>
    roleTypes: [CODIS_PROXY]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: codis.proxy.container.requests.memory
  recommendExpression: -1
  defaultValue: null
  valueType: FLOAT
  scope: !<RoleTypes>
    roleTypes: [CODIS_PROXY]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: codis.proxy.container.requests.cpu
  recommendExpression: -1
  defaultValue: null
  valueType: FLOAT
  scope: !<RoleTypes>
    roleTypes: [CODIS_PROXY]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: codis.proxy.auth
  recommendExpression: ""
  defaultValue: null
  valueType: STRING
  scope: !<RoleTypes>
    roleTypes: [CODIS_PROXY]
  onDeps: []
  groups: []
  visibility: PASSWORD

#fe
- name: codis.fe.container.limits.memory
  recommendExpression: -1
  defaultValue: null
  valueType: FLOAT
  scope: !<RoleTypes>
    roleTypes: [CODIS_FE]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: codis.fe.container.limits.cpu
  recommendExpression: -1
  defaultValue: null
  valueType: FLOAT
  scope: !<RoleTypes>
    roleTypes: [CODIS_FE]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: codis.fe.container.requests.memory
  recommendExpression: -1
  defaultValue: null
  valueType: FLOAT
  scope: !<RoleTypes>
    roleTypes: [CODIS_FE]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: codis.fe.container.requests.cpu
  recommendExpression: -1
  defaultValue: null
  valueType: FLOAT
  scope: !<RoleTypes>
    roleTypes: [CODIS_FE]
  onDeps: []
  groups: []
  visibility: READ_WRITE

#server
- name: codis.server.container.limits.memory
  recommendExpression: -1
  defaultValue: null
  valueType: FLOAT
  scope: !<RoleTypes>
    roleTypes: [CODIS_SERVER]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: codis.server.container.limits.cpu
  recommendExpression: -1
  defaultValue: null
  valueType: FLOAT
  scope: !<RoleTypes>
    roleTypes: [CODIS_SERVER]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: codis.server.container.requests.memory
  recommendExpression: -1
  defaultValue: null
  valueType: FLOAT
  scope: !<RoleTypes>
    roleTypes: [CODIS_SERVER]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: codis.server.container.requests.cpu
  recommendExpression: -1
  defaultValue: null
  valueType: FLOAT
  scope: !<RoleTypes>
    roleTypes: [CODIS_SERVER]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: codis.product.name
  recommendExpression: default
  defaultValue: null
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: codis.fe.port
  recommendExpression: 9090
  defaultValue: null
  valueType: NON_NEG_INT
  scope: !<RoleTypes>
    roleTypes: [CODIS_FE]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: codis.cluster.auth
  recommendExpression: ""
  defaultValue: null
  valueType: STRING
  scope: !<RoleTypes>
    roleTypes: [CODIS_PROXY, CODIS_SERVER, CODIS_DASHBOARD]
  onDeps: []
  groups: []
  visibility: PASSWORD