# the general settings for mirror application
app:
  # the application name
  name: ${service.sid}
  # indicates whether mirror works under access control
  access-control: true


# web container config
server.port: ${service['mirror.userprofile.port']}
