- name: inceptor.server.version
  recommendExpression: "tdh60"
  defaultValue: "tdh60"
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: inceptor.gateway.port
  recommendExpression: 6666
  defaultValue: 6666
  valueType: PORT
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: inceptor.gateway.ui.port
  recommendExpression: 6060
  defaultValue: 6060
  valueType: PORT
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: inceptor.gateway.host
  recommendExpression: 0.0.0.0
  defaultValue: 0.0.0.0
  valueType: HOST_PORT
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: inceptor.gateway.conf.dir
  recommendExpression: /usr/lib/gateway/conf
  defaultValue: /usr/lib/gateway/conf
  valueType: ABSOLUTE_PATH
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: inceptor.gateway.connection.failretry.ms
  recommendExpression: 10000
  defaultValue: 10000
  valueType: MILLISECONDS
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: inceptor.gateway.system.timeout.ms
  recommendExpression: 14400000
  defaultValue: 14400000
  valueType: MILLISECONDS
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: inceptor.gateway.thrift.min.workers
  recommendExpression: 1
  defaultValue: 1
  valueType: NON_NEG_INT
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: READ_WRITE


- name: inceptor.gateway.thrift.max.workers
  recommendExpression: 300
  defaultValue: 300
  valueType: NON_NEG_INT
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: inceptor.gateway.session.idle.timeout.ms
  recommendExpression: 60000
  defaultValue: 60000
  valueType: MILLISECONDS
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: READ_WRITE


- name: inceptor.gateway.hive.parser.enabled
  recommendExpression: true
  defaultValue: true
  valueType: BOOL
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: inceptor.gateway.hive.parser.warmup
  recommendExpression: true
  defaultValue: true
  valueType: BOOL
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: inceptor.gateway.backend.server.default.version
  recommendExpression: tdh60
  defaultValue: tdh60
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: inceptor.gateway.check.server.interval
  recommendExpression: 3000
  defaultValue: 3000
  valueType: MILLISECONDS
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: inceptor.gateway.ha.slave.connect.retry.times
  recommendExpression: 10
  defaultValue: 10
  valueType: NON_NEG_INT
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: inceptor.gateway.ha.slave.retry.interval
  recommendExpression: 10000
  defaultValue: 10000
  valueType: MILLISECONDS
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: inceptor.gateway.pick.server.mode
  recommendExpression: ROUND-ROBIN
  defaultValue: ROUND-ROBIN
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: inceptor.gateway.conf.file.format
  recommendExpression: xml
  defaultValue: xml
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: inceptor.gateway.used.slipstream
  recommendExpression: false
  defaultValue: false
  valueType: BOOL
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: inceptor.gateway.audit.max.sql.length
  recommendExpression: 128
  defaultValue: 128
  valueType: NON_NEG_INT
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: READ_WRITE
