- name: inceptor.server.version
  recommendExpression: "tdh60"
  defaultValue: "tdh60"
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: inceptor.gateway.port
  recommendExpression: 6666
  defaultValue: 6666
  valueType: PORT
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: inceptor.gateway.ui.port
  recommendExpression: 6060
  defaultValue: 6060
  valueType: PORT
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: READ_WRITE

