# application-prod.properties
- name: backend.port
  recommendExpression: 8897
  defaultValue: null
  valueType: PORT
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: javax.jdo.option.ConnectionUserName
  recommendExpression: datamarket
  defaultValue: null
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: javax.jdo.option.ConnectionPassword
  recommendExpression: password
  defaultValue: null
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: PASSWORD

- name: backend.limits.memory
  recommendExpression: -1
  defaultValue: null
  valueType: GB
  scope: !<RoleTypes>
    roleTypes: [DATAMARKET_BACKEND]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: backend.limits.cpu
  recommendExpression: -1
  defaultValue: null
  valueType: NON_NEG_INT
  scope: !<RoleTypes>
    roleTypes: [DATAMARKET_BACKEND]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: backend.requests.memory
  recommendExpression: -1
  defaultValue: null
  valueType: GB
  scope: !<RoleTypes>
    roleTypes: [DATAMARKET_BACKEND]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: backend.requests.cpu
  recommendExpression: -1
  defaultValue: null
  valueType: NON_NEG_INT
  scope: !<RoleTypes>
    roleTypes: [DATAMARKET_BACKEND]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: frontend.port
  recommendExpression: 8898
  defaultValue: null
  valueType: PORT
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: frontend.limits.memory
  recommendExpression: -1
  defaultValue: null
  valueType: GB
  scope: !<RoleTypes>
    roleTypes: [DATAMARKET_BACKEND]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: frontend.limits.cpu
  recommendExpression: -1
  defaultValue: null
  valueType: NON_NEG_INT
  scope: !<RoleTypes>
    roleTypes: [DATAMARKET_BACKEND]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: frontend.requests.memory
  recommendExpression: -1
  defaultValue: null
  valueType: GB
  scope: !<RoleTypes>
    roleTypes: [DATAMARKET_BACKEND]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: frontend.requests.cpu
  recommendExpression: -1
  defaultValue: null
  valueType: NON_NEG_INT
  scope: !<RoleTypes>
    roleTypes: [DATAMARKET_BACKEND]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: inceptor.ldap.username
  recommendExpression: mirror
  defaultValue: null
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: inceptor.ldap.password
  recommendExpression: password
  defaultValue: null
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: PASSWORD

- name: distributed.database.type
  recommendExpression: inceptor
  defaultValue: null
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: READ_WRITE
