apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    transwarp.name: coredns-entrypoint-cm
  name: coredns-entrypoint-cm
  namespace: kube-system
data:
  entrypoint.sh: |-
    #!/bin/bash
    set -x

    coredns -conf /conf/Corefile
