apiVersion: v1
data:
<#list dependencies.TOS.roles.TOS_SLAVE as tos_slave>
  ${tos_slave.hostname}: ${tos_slave.ip}
</#list>
kind: ConfigMap
metadata:
  labels:
    transwarp.io/user_defined_dns: "true"
  name: toshost
  namespace: kube-system