- name: designer.server.port
  recommendExpression: 32125
  defaultValue: null
  valueType: PORT
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: designer.global.session.timeout.secs
  recommendExpression: 3600
  defaultValue: null
  valueType: NON_NEG_INT
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: connectionpool.expiretime
  recommendExpression: 30
  defaultValue: null
  valueType: NON_NEG_INT
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: cube.group.max.size
  recommendExpression: 30000
  defaultValue: null
  valueType: NON_NEG_INT
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: cube.group.optimize
  recommendExpression: true
  defaultValue: null
  valueType: BOOL
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: rubik.rest.api.detail
  recommendExpression: false
  defaultValue: null
  valueType: BOOL
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: subtask.execute.max.size
  recommendExpression: 50
  defaultValue: null
  valueType: NON_NEG_INT
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: cubeparser.enabalejoinhint
  recommendExpression: false
  defaultValue: null
  valueType: BOOL
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: notification.server.addr
  recommendExpression: 0.0.0.0
  defaultValue: null
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: service.rest.sleep.interval.ms
  recommendExpression: 3000
  defaultValue: null
  valueType: NON_NEG_INT
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: service.rest.retries
  recommendExpression: 3
  defaultValue: null
  valueType: NON_NEG_INT
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: service.rest.readTimeoutMSecs
  recommendExpression: 60000
  defaultValue: null
  valueType: NON_NEG_INT
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: service.rest.connectTimeoutMSecs
  recommendExpression: 60000
  defaultValue: null
  valueType: NON_NEG_INT
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: service.checker.sleep.interval.min
  recommendExpression: 2
  defaultValue: null
  valueType: NON_NEG_INT
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: rubik.memory
  recommendExpression: 2048
  defaultValue: null
  valueType: MB
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: javax.jdo.option.ConnectionUserName
  recommendExpression: rubikuser
  defaultValue: null
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: javax.jdo.option.ConnectionPassword
  recommendExpression: password
  defaultValue: null
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: PASSWORD

- name: rubik.container.limits.memory
  recommendExpression: -1
  defaultValue: null
  valueType: GB
  scope: !<RoleTypes>
    roleTypes: [RUBIK_SERVER]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: rubik.container.limits.cpu
  recommendExpression: -1
  defaultValue: null
  valueType: NON_NEG_INT
  scope: !<RoleTypes>
    roleTypes: [RUBIK_SERVER]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: rubik.container.requests.memory
  recommendExpression: -1
  defaultValue: null
  valueType: GB
  scope: !<RoleTypes>
    roleTypes: [RUBIK_SERVER]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: rubik.container.requests.cpu
  recommendExpression: -1
  defaultValue: null
  valueType: NON_NEG_INT
  scope: !<RoleTypes>
    roleTypes: [RUBIK_SERVER]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: rubik.memory.ratio
  recommendExpression: -1
  defaultValue: null
  valueType: FLOAT
  scope: !<RoleTypes>
    roleTypes: [RUBIK_SERVER]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: workflow.connect.timeout
  recommendExpression: 60000
  defaultValue: null
  valueType: NON_NEG_INT
  scope: !<RoleTypes>
    roleTypes: [RUBIK_SERVER]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: workflow.socket.timeout
  recommendExpression: 60000
  defaultValue: null
  valueType: NON_NEG_INT
  scope: !<RoleTypes>
    roleTypes: [RUBIK_SERVER]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: workflow.client.username
  recommendExpression: workflow
  defaultValue: null
  valueType: STRING
  scope: !<RoleTypes>
    roleTypes: [RUBIK_SERVER]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: workflow.client.password
  recommendExpression: Transwarp4T
  defaultValue: null
  valueType: STRING
  scope: !<RoleTypes>
    roleTypes: [RUBIK_SERVER]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: inceptor.database.username
  recommendExpression: inceptor
  defaultValue: null
  valueType: STRING
  scope: !<RoleTypes>
    roleTypes: [RUBIK_SERVER]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: inceptor.database.password
  recommendExpression: 123
  defaultValue: null
  valueType: STRING
  scope: !<RoleTypes>
    roleTypes: [RUBIK_SERVER]
  onDeps: []
  groups: []
  visibility: READ_WRITE
