- name: kms.http.port
  recommendExpression: 16000
  defaultValue: null
  valueType: PORT
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: kms.admin.port
  recommendExpression: 16001
  defaultValue: null
  valueType: PORT
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: kms.db.encrypt.key.password
  recommendExpression: Str0ngPassw0rd
  defaultValue: null
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: javax.jdo.option.ConnectionUserName
  recommendExpression: kmsuser
  defaultValue: null
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: javax.jdo.option.ConnectionPassword
  recommendExpression: password
  defaultValue: null
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: PASSWORD

- name: hadoop.kms.acl.CREATE
  recommendExpression: "keyadmin"
  defaultValue: null
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: [kms-acls.xml]
  visibility: READ_WRITE

- name: hadoop.kms.blacklist.CREATE
  recommendExpression: "hdfs,admin"
  defaultValue: null
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: [kms-acls.xml]
  visibility: READ_WRITE

- name: hadoop.kms.acl.DELETE
  recommendExpression: keyadmin
  defaultValue: null
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: [kms-acls.xml]
  visibility: READ_WRITE

- name: hadoop.kms.blacklist.DELETE
  recommendExpression: "hdfs,admin"
  defaultValue: null
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: [kms-acls.xml]
  visibility: READ_WRITE

- name: hadoop.kms.acl.ROLLOVER
  recommendExpression: "keyadmin"
  defaultValue: null
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: [kms-acls.xml]
  visibility: READ_WRITE

- name: hadoop.kms.blacklist.ROLLOVER
  recommendExpression: "hdfs,admin"
  defaultValue: null
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: [kms-acls.xml]
  groups: []
  visibility: READ_WRITE

- name: hadoop.kms.acl.GET
  recommendExpression: "*"
  defaultValue: null
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: [kms-acls.xml]
  visibility: READ_WRITE

- name: hadoop.kms.blacklist.GET
  recommendExpression: "*"
  defaultValue: null
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: [kms-acls.xml]
  visibility: READ_WRITE

- name: hadoop.kms.acl.GET_KEYS
  recommendExpression: "*"
  defaultValue: null
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: [kms-acls.xml]
  visibility: READ_WRITE

- name: hadoop.kms.blacklist.GET_KEYS
  recommendExpression: null
  defaultValue: null
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: [kms-acls.xml]
  visibility: READ_WRITE

- name: hadoop.kms.acl.GET_METADATA
  recommendExpression: "*"
  defaultValue: null
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: [kms-acls.xml]
  visibility: READ_WRITE

- name: hadoop.kms.blacklist.GET_METADATA
  recommendExpression: null
  defaultValue: null
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: [kms-acls.xml]
  visibility: READ_WRITE

- name: hadoop.kms.acl.SET_KEY_MATERIAL
  recommendExpression: null
  defaultValue: null
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: [kms-acls.xml]
  visibility: READ_WRITE

- name: hadoop.kms.blacklist.SET_KEY_MATERIAL
  recommendExpression: "*"
  defaultValue: null
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: [kms-acls.xml]
  visibility: READ_WRITE

- name: hadoop.kms.acl.GENERATE_EEK
  recommendExpression: "hdfs"
  defaultValue: null
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: [kms-acls.xml]
  visibility: READ_WRITE

- name: hadoop.kms.blacklist.GENERATE_EEK
  recommendExpression: null
  defaultValue: null
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: [kms-acls.xml]
  visibility: READ_WRITE

- name: hadoop.kms.acl.DECRYPT_EEK
  recommendExpression: "*"
  defaultValue: null
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: [kms-acls.xml]
  visibility: READ_WRITE

- name: hadoop.kms.blacklist.DECRYPT_EEK
  recommendExpression: "hdfs,admin"
  defaultValue: null
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: [kms-acls.xml]
  visibility: READ_WRITE

- name: whitelist.key.acl.MANAGEMENT
  recommendExpression: keyadmin
  defaultValue: null
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: [kms-acls.xml]
  visibility: READ_WRITE

- name: whitelist.key.acl.READ
  recommendExpression: hdfs
  defaultValue: null
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: [kms-acls.xml]
  visibility: READ_WRITE

- name: whitelist.key.acl.GENERATE_EEK
  recommendExpression: hdfs
  defaultValue: null
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: [kms-acls.xml]
  visibility: READ_WRITE

- name: whitelist.key.acl.DECRYPT_EEK
  recommendExpression: null
  defaultValue: null
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: [kms-acls.xml]
  visibility: READ_WRITE

- name: default.key.acl.MANAGEMENT
  recommendExpression: null
  defaultValue: null
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: [kms-acls.xml]
  visibility: READ_WRITE

- name: default.key.acl.GENERATE_EEK
  recommendExpression: null
  defaultValue: null
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: [kms-acls.xml]
  visibility: READ_WRITE

- name: default.key.acl.DECRYPT_EEK
  recommendExpression: null
  defaultValue: null
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: [kms-acls.xml]
  visibility: READ_WRITE

- name: default.key.acl.READ
  recommendExpression: null
  defaultValue: null
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: [kms-acls.xml]
  visibility: READ_WRITE

- name: kms.container.limits.memory
  recommendExpression: -1
  defaultValue: null
  valueType: GB
  scope: !<RoleTypes>
    roleTypes: [KMS_SERVER]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: kms.container.limits.cpu
  recommendExpression: -1
  defaultValue: null
  valueType: NON_NEG_INT
  scope: !<RoleTypes>
    roleTypes: [KMS_SERVER]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: kms.container.requests.memory
  recommendExpression: -1
  defaultValue: null
  valueType: GB
  scope: !<RoleTypes>
    roleTypes: [KMS_SERVER]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: kms.container.requests.cpu
  recommendExpression: -1
  defaultValue: null
  valueType: NON_NEG_INT
  scope: !<RoleTypes>
    roleTypes: [KMS_SERVER]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: kms.memory.ratio
  recommendExpression: -1
  defaultValue: null
  valueType: FLOAT
  scope: !<RoleTypes>
    roleTypes: [KMS_SERVER]
  onDeps: []
  groups: []
  visibility: READ_WRITE
