<#assign tosService=dependencies.TOS>
apiVersion: v1
kind: Service
metadata:
  labels:
    transwarp.name: kube-dns-${service.sid}
  name: kube-dns-${service.sid}
  namespace: kube-system
spec:
  clusterIP: ${tosService['cluster.dns.ip']}
  ports:
  - name: dns
    port: ${service['kube.dns.dnsmasq.port']}
    protocol: UDP
    targetPort: ${service['kube.dns.dnsmasq.port']}
  - name: dns-tcp
    port: ${service['kube.dns.dnsmasq.port']}
    protocol: TCP
    targetPort: ${service['kube.dns.dnsmasq.port']}
  selector:
    transwarp.name: kube-dns-${service.sid}
  type: NodePort
