- name: data.dir
  recommendExpression: |
    <#function localDir suffix>
      <#if rcmdMounts?size == 0>
        <#return suffix>
      <#else>
        <#return (rcmdMounts?sort)[0] + suffix >
      </#if>
    </#function>
    ${localDir("/hadoop/" + service['sid'])}
  defaultValue: null
  valueType: ABSOLUTE_PATH
  scope: !<RoleTypes>
    roleTypes: [TXSQL_SERVER]
  isNodeSpecific: true
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: log.dir
  recommendExpression: ${"/var/log/" + service['sid']}
  defaultValue: null
  valueType: ABSOLUTE_PATH
  scope: !<RoleTypes>
    roleTypes: [TXSQL_SERVER]
  isNodeSpecific: true
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: mysql.rw.port
  recommendExpression: 3316
  defaultValue: null
  valueType: PORT
  scope: !<RoleTypes>
    roleTypes: [TXSQL_SERVER]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: binlog.port
  recommendExpression: 6000
  defaultValue: null
  valueType: PORT
  scope: !<RoleTypes>
    roleTypes: [TXSQL_SERVER]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: mysql.local.port
  recommendExpression: 13306
  defaultValue: null
  valueType: PORT
  scope: !<RoleTypes>
    roleTypes: [TXSQL_SERVER]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: binlogsvr.rpc.port
  recommendExpression: 17000
  defaultValue: null
  valueType: PORT
  scope: !<RoleTypes>
    roleTypes: [TXSQL_SERVER]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: paxos.port
  recommendExpression: 8001
  defaultValue: null
  valueType: PORT
  scope: !<RoleTypes>
    roleTypes: [TXSQL_SERVER]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: root.password
  recommendExpression: ${(service['root.password']??)?then(service['root.password'],((.now?long * .now?long)%987654321)?abs?c)}
  defaultValue: null
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: HIDDEN

- name: txsql.container.limits.memory
  recommendExpression: -1
  defaultValue: null
  valueType: FLOAT
  scope: !<RoleTypes>
    roleTypes: [TXSQL_SERVER]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: txsql.container.limits.cpu
  recommendExpression: -1
  defaultValue: null
  valueType: FLOAT
  scope: !<RoleTypes>
    roleTypes: [TXSQL_SERVER]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: txsql.container.requests.memory
  recommendExpression: -1
  defaultValue: null
  valueType: FLOAT
  scope: !<RoleTypes>
    roleTypes: [TXSQL_SERVER]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: txsql.container.requests.cpu
  recommendExpression: -1
  defaultValue: null
  valueType: FLOAT
  scope: !<RoleTypes>
    roleTypes: [TXSQL_SERVER]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: txsql.memory.ratio
  recommendExpression: -1
  defaultValue: null
  valueType: FLOAT
  scope: !<RoleTypes>
    roleTypes: [TXSQL_SERVER]
  onDeps: []
  groups: []
  visibility: READ_WRITE